# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualClusteringGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_matplotlib = MplWidget(self.centralwidget)
        self.widget_matplotlib.setGeometry(QtCore.QRect(305, 9, 944, 779))
        self.widget_matplotlib.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_matplotlib.setObjectName("widget_matplotlib")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 80, 290, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(290, 120))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 90, 201, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setScaledContents(False)
        self.label_15.setWordWrap(True)
        self.label_15.setOpenExternalLinks(True)
        self.label_15.setObjectName("label_15")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 271, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setToolTip("")
        self.label_16.setOpenExternalLinks(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.doubleSpinBox_distance = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_distance.setMaximumSize(QtCore.QSize(90, 16777215))
        self.doubleSpinBox_distance.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_distance.setDecimals(0)
        self.doubleSpinBox_distance.setMinimum(3.0)
        self.doubleSpinBox_distance.setMaximum(999999.0)
        self.doubleSpinBox_distance.setProperty("value", 30.0)
        self.doubleSpinBox_distance.setObjectName("doubleSpinBox_distance")
        self.gridLayout.addWidget(self.doubleSpinBox_distance, 0, 1, 1, 1)
        self.horizontalSlider_distance = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_distance.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_distance.setSizePolicy(sizePolicy)
        self.horizontalSlider_distance.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSlider_distance.setMinimum(10)
        self.horizontalSlider_distance.setMaximum(100)
        self.horizontalSlider_distance.setProperty("value", 30)
        self.horizontalSlider_distance.setSliderPosition(30)
        self.horizontalSlider_distance.setTracking(False)
        self.horizontalSlider_distance.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_distance.setObjectName("horizontalSlider_distance")
        self.gridLayout.addWidget(self.horizontalSlider_distance, 0, 2, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 60, 271, 32))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox_min_points = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_min_points.setToolTip("")
        self.doubleSpinBox_min_points.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_min_points.setDecimals(0)
        self.doubleSpinBox_min_points.setMinimum(4.0)
        self.doubleSpinBox_min_points.setMaximum(1000.0)
        self.doubleSpinBox_min_points.setProperty("value", 8.0)
        self.doubleSpinBox_min_points.setObjectName("doubleSpinBox_min_points")
        self.gridLayout_2.addWidget(self.doubleSpinBox_min_points, 0, 1, 1, 1)
        self.horizontalSlider_min_points = QtWidgets.QSlider(self.layoutWidget_2)
        self.horizontalSlider_min_points.setToolTip("")
        self.horizontalSlider_min_points.setMinimum(4)
        self.horizontalSlider_min_points.setMaximum(30)
        self.horizontalSlider_min_points.setSliderPosition(8)
        self.horizontalSlider_min_points.setTracking(False)
        self.horizontalSlider_min_points.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_min_points.setObjectName("horizontalSlider_min_points")
        self.gridLayout_2.addWidget(self.horizontalSlider_min_points, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setToolTip("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(9, 206, 280, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(280, 250))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(11, 13, 241, 31))
        self.label_2.setObjectName("label_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 50, 261, 238))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 2, 1, 1)
        self.lineEdit_min_size = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_min_size.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_min_size.setObjectName("lineEdit_min_size")
        self.gridLayout_3.addWidget(self.lineEdit_min_size, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 1, 1, 1)
        self.lineEdit_max_size = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_max_size.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_max_size.setObjectName("lineEdit_max_size")
        self.gridLayout_3.addWidget(self.lineEdit_max_size, 1, 2, 1, 1)
        self.lineEdit_min_density = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_min_density.setEnabled(True)
        self.lineEdit_min_density.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_min_density.setObjectName("lineEdit_min_density")
        self.gridLayout_3.addWidget(self.lineEdit_min_density, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setEnabled(True)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 1, 1, 1)
        self.lineEdit_max_density = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_max_density.setEnabled(True)
        self.lineEdit_max_density.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_max_density.setObjectName("lineEdit_max_density")
        self.gridLayout_3.addWidget(self.lineEdit_max_density, 2, 2, 1, 1)
        self.lineEdit_min_roundness = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_min_roundness.setEnabled(True)
        self.lineEdit_min_roundness.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_min_roundness.setObjectName("lineEdit_min_roundness")
        self.gridLayout_3.addWidget(self.lineEdit_min_roundness, 3, 0, 1, 1)
        self.lineEdit_max_roundness = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_max_roundness.setEnabled(True)
        self.lineEdit_max_roundness.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_max_roundness.setObjectName("lineEdit_max_roundness")
        self.gridLayout_3.addWidget(self.lineEdit_max_roundness, 3, 2, 1, 1)
        self.lineEdit_ch1_min = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ch1_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ch1_min.setObjectName("lineEdit_ch1_min")
        self.gridLayout_3.addWidget(self.lineEdit_ch1_min, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 1, 1, 1)
        self.lineEdit_ch1_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ch1_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ch1_max.setObjectName("lineEdit_ch1_max")
        self.gridLayout_3.addWidget(self.lineEdit_ch1_max, 4, 2, 1, 1)
        self.lineEdit_ch2_min = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ch2_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ch2_min.setObjectName("lineEdit_ch2_min")
        self.gridLayout_3.addWidget(self.lineEdit_ch2_min, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 5, 1, 1, 1)
        self.lineEdit_ch2_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ch2_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ch2_max.setObjectName("lineEdit_ch2_max")
        self.gridLayout_3.addWidget(self.lineEdit_ch2_max, 5, 2, 1, 1)
        self.lineEdit_ch3_min = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ch3_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ch3_min.setObjectName("lineEdit_ch3_min")
        self.gridLayout_3.addWidget(self.lineEdit_ch3_min, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 6, 1, 1, 1)
        self.lineEdit_ch3_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ch3_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ch3_max.setObjectName("lineEdit_ch3_max")
        self.gridLayout_3.addWidget(self.lineEdit_ch3_max, 6, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_14.setEnabled(True)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(9, 500, 290, 100))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 245, 68))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setToolTip("")
        self.label_19.setOpenExternalLinks(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.doubleSpinBox_top_edge = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_top_edge.setDecimals(0)
        self.doubleSpinBox_top_edge.setMaximum(100.0)
        self.doubleSpinBox_top_edge.setProperty("value", 0.0)
        self.doubleSpinBox_top_edge.setObjectName("doubleSpinBox_top_edge")
        self.gridLayout_4.addWidget(self.doubleSpinBox_top_edge, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_22.setToolTip("")
        self.label_22.setOpenExternalLinks(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 2, 1, 1)
        self.doubleSpinBox_left_edge = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_left_edge.setDecimals(0)
        self.doubleSpinBox_left_edge.setMaximum(100.0)
        self.doubleSpinBox_left_edge.setProperty("value", 0.0)
        self.doubleSpinBox_left_edge.setObjectName("doubleSpinBox_left_edge")
        self.gridLayout_4.addWidget(self.doubleSpinBox_left_edge, 0, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_20.setToolTip("")
        self.label_20.setOpenExternalLinks(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.doubleSpinBox_bottom_edge = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_bottom_edge.setDecimals(0)
        self.doubleSpinBox_bottom_edge.setMaximum(100.0)
        self.doubleSpinBox_bottom_edge.setProperty("value", 0.0)
        self.doubleSpinBox_bottom_edge.setObjectName("doubleSpinBox_bottom_edge")
        self.gridLayout_4.addWidget(self.doubleSpinBox_bottom_edge, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_21.setToolTip("")
        self.label_21.setOpenExternalLinks(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 1, 2, 1, 1)
        self.doubleSpinBox_right_edge = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_right_edge.setDecimals(0)
        self.doubleSpinBox_right_edge.setMaximum(100.0)
        self.doubleSpinBox_right_edge.setProperty("value", 0.0)
        self.doubleSpinBox_right_edge.setObjectName("doubleSpinBox_right_edge")
        self.gridLayout_4.addWidget(self.doubleSpinBox_right_edge, 1, 3, 1, 1)
        self.textEdit_avgs = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_avgs.setGeometry(QtCore.QRect(9, 638, 250, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_avgs.sizePolicy().hasHeightForWidth())
        self.textEdit_avgs.setSizePolicy(sizePolicy)
        self.textEdit_avgs.setMaximumSize(QtCore.QSize(250, 150))
        self.textEdit_avgs.setReadOnly(True)
        self.textEdit_avgs.setObjectName("textEdit_avgs")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 600, 107, 18))
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setObjectName("label_3")
        self.spinBox_resolution = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_resolution.setGeometry(QtCore.QRect(123, 600, 105, 28))
        self.spinBox_resolution.setMaximumSize(QtCore.QSize(120, 16777215))
        self.spinBox_resolution.setMaximum(5096)
        self.spinBox_resolution.setProperty("value", 0)
        self.spinBox_resolution.setObjectName("spinBox_resolution")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 10, 271, 64))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(40, 20))
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_wells = QtWidgets.QComboBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_wells.sizePolicy().hasHeightForWidth())
        self.comboBox_wells.setSizePolicy(sizePolicy)
        self.comboBox_wells.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox_wells.setObjectName("comboBox_wells")
        self.gridLayout_5.addWidget(self.comboBox_wells, 0, 1, 1, 1)
        self.pushButton_done = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_done.sizePolicy().hasHeightForWidth())
        self.pushButton_done.setSizePolicy(sizePolicy)
        self.pushButton_done.setObjectName("pushButton_done")
        self.gridLayout_5.addWidget(self.pushButton_done, 0, 2, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(40, 20))
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBox_color = QtWidgets.QComboBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_color.sizePolicy().hasHeightForWidth())
        self.comboBox_color.setSizePolicy(sizePolicy)
        self.comboBox_color.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox_color.setObjectName("comboBox_color")
        self.gridLayout_5.addWidget(self.comboBox_color, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Cluster parameters"))
        self.label_15.setToolTip(_translate("MainWindow", "Click to reat more about the DBSCAN clustering algorithm and its parameters"))
        self.label_15.setStatusTip(_translate("MainWindow", "Click to reat more about the DBSCAN clustering algorithm and its parameters"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"http://en.wikipedia.org/wiki/DBSCAN\"><span style=\" font-size:7pt; text-decoration: underline; color:#000000;\">Read more about these parameters on wikipedia</span></a></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>ε-Distance</p></body></html>"))
        self.doubleSpinBox_distance.setSuffix(_translate("MainWindow", " µm"))
        self.doubleSpinBox_min_points.setSuffix(_translate("MainWindow", " cells"))
        self.label_17.setText(_translate("MainWindow", "MinPoints"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Filters"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-style:italic; color:#393939; vertical-align:sub;\">Press enter to redraw plot</span></p></body></html>"))
        self.label_10.setToolTip(_translate("MainWindow", "Colonies outside one of these ranges are not included in the analysis (but they are still plotted)"))
        self.label_10.setStatusTip(_translate("MainWindow", "Colonies outside one of these ranges are not included in the analysis (but they are still plotted)"))
        self.label_10.setText(_translate("MainWindow", "Min"))
        self.label_12.setToolTip(_translate("MainWindow", "Colonies outside one of these ranges are not included in the analysis (but they are still plotted)"))
        self.label_12.setStatusTip(_translate("MainWindow", "Colonies outside one of these ranges are not included in the analysis (but they are still plotted)"))
        self.label_12.setText(_translate("MainWindow", "Colony Property"))
        self.label_11.setToolTip(_translate("MainWindow", "Colonies outside one of these ranges are not included in the analysis (but they are still plotted)"))
        self.label_11.setStatusTip(_translate("MainWindow", "Colonies outside one of these ranges are not included in the analysis (but they are still plotted)"))
        self.label_11.setText(_translate("MainWindow", "Max"))
        self.lineEdit_min_size.setToolTip(_translate("MainWindow", "The number of cells in a colony"))
        self.lineEdit_min_size.setStatusTip(_translate("MainWindow", "The number of cells in a colony"))
        self.lineEdit_min_size.setText(_translate("MainWindow", "5"))
        self.label_7.setToolTip(_translate("MainWindow", "The number of cells in a colony"))
        self.label_7.setStatusTip(_translate("MainWindow", "The number of cells in a colony"))
        self.label_7.setText(_translate("MainWindow", "Size (cells)"))
        self.lineEdit_max_size.setToolTip(_translate("MainWindow", "The number of cells in a colony"))
        self.lineEdit_max_size.setStatusTip(_translate("MainWindow", "The number of cells in a colony"))
        self.lineEdit_max_size.setText(_translate("MainWindow", "99999"))
        self.lineEdit_min_density.setToolTip(_translate("MainWindow", " Cells per megapixel. The exact number depends on the resolution of the scan, but can always be used as an arbitrary density measurement"))
        self.lineEdit_min_density.setText(_translate("MainWindow", "0"))
        self.label_13.setToolTip(_translate("MainWindow", " Cells per megapixel. The exact number depends on the resolution of the scan, but can always be used as an arbitrary density measurement"))
        self.label_13.setStatusTip(_translate("MainWindow", "If the colony area would be enlarged to 1 mm2, the colony would contain this many cells"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Density</p></body></html>"))
        self.lineEdit_max_density.setToolTip(_translate("MainWindow", " Cells per megapixel. The exact number depends on the resolution of the scan, but can always be used as an arbitrary density measurement"))
        self.lineEdit_max_density.setText(_translate("MainWindow", "9999999"))
        self.lineEdit_min_roundness.setToolTip(_translate("MainWindow", "<html><head/><body><p>Compares the area of a colony (as a polygon) with a theoretical perfectly circular colony. The maximum value is 1, which would mean that the colony is circular with cells all along the perimeter.</p><p>The perfectly circular colony has a radius that equals the distance between the mean loction of all cells in the colony and the location of the cell the furthest away from this mean.</p><p><br/></p></body></html>"))
        self.lineEdit_min_roundness.setStatusTip(_translate("MainWindow", "Compares the area of a colony (as a polygon) with a theoretical perfectly circular colony. The maximum value is 1, which would mean that the colony is circular with cells all along the perimeter.</p><p>The perfectly circular colony has a radius that equals the distance between the mean loction of all cells in the colony and the location of the cell the furthest away from this mean."))
        self.lineEdit_min_roundness.setText(_translate("MainWindow", "0"))
        self.lineEdit_max_roundness.setToolTip(_translate("MainWindow", "<html><head/><body><p>Compares the area of a colony (as a polygon) with a theoretical perfectly circular colony. The maximum value is 1, which would mean that the colony is circular with cells all along the perimeter.</p><p>The perfectly circular colony has a radius that equals the distance between the mean loction of all cells in the colony and the location of the cell the furthest away from this mean.</p><p><br/></p></body></html>"))
        self.lineEdit_max_roundness.setStatusTip(_translate("MainWindow", "Compares the area of a colony (as a polygon) with a theoretical perfectly circular colony. The maximum value is 1, which would mean that the colony is circular with cells all along the perimeter.</p><p>The perfectly circular colony has a radius that equals the distance between the mean loction of all cells in the colony and the location of the cell the furthest away from this mean."))
        self.lineEdit_max_roundness.setText(_translate("MainWindow", "1"))
        self.lineEdit_ch1_min.setToolTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch1_min.setStatusTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch1_min.setText(_translate("MainWindow", "0"))
        self.label_8.setToolTip(_translate("MainWindow", "Intensity"))
        self.label_8.setStatusTip(_translate("MainWindow", "Intensity"))
        self.label_8.setText(_translate("MainWindow", "Ch1"))
        self.lineEdit_ch1_max.setToolTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch1_max.setStatusTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch1_max.setText(_translate("MainWindow", "9999"))
        self.lineEdit_ch2_min.setToolTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch2_min.setStatusTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch2_min.setText(_translate("MainWindow", "0"))
        self.label_9.setToolTip(_translate("MainWindow", "Intensity"))
        self.label_9.setStatusTip(_translate("MainWindow", "Intensity"))
        self.label_9.setText(_translate("MainWindow", "Ch2"))
        self.lineEdit_ch2_max.setToolTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch2_max.setStatusTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch2_max.setText(_translate("MainWindow", "9999"))
        self.lineEdit_ch3_min.setToolTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch3_min.setStatusTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch3_min.setText(_translate("MainWindow", "0"))
        self.label_18.setToolTip(_translate("MainWindow", "Intensity"))
        self.label_18.setStatusTip(_translate("MainWindow", "Intensity"))
        self.label_18.setText(_translate("MainWindow", "Ch3"))
        self.lineEdit_ch3_max.setToolTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch3_max.setStatusTip(_translate("MainWindow", "Intensity"))
        self.lineEdit_ch3_max.setText(_translate("MainWindow", "9999"))
        self.label_14.setToolTip(_translate("MainWindow", "<html><head/><body><p>Compares the area of a colony (as a polygon) with a theoretical perfectly circular colony. The formula is (4*PI)* PI*R² / 4PI²R² and the maximum value is 1, which would mean that the colony is circular with cells all along the perimeter.</p></body></html>"))
        self.label_14.setStatusTip(_translate("MainWindow", "Compares the area of a colony (as a polygon) with a theoretical perfectly circular colony. The formula is (4*PI)* PI*R² / 4PI²R² and the maximum value is 1, which would mean that the colony is circular with cells all along the perimeter."))
        self.label_14.setText(_translate("MainWindow", "Roundness"))
        self.groupBox.setTitle(_translate("MainWindow", "Edge exclusion"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Top</p></body></html>"))
        self.doubleSpinBox_top_edge.setSuffix(_translate("MainWindow", "%"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p>Left</p></body></html>"))
        self.doubleSpinBox_left_edge.setSuffix(_translate("MainWindow", "%"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p>Bottom</p></body></html>"))
        self.doubleSpinBox_bottom_edge.setSuffix(_translate("MainWindow", "%"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Right</p></body></html>"))
        self.doubleSpinBox_right_edge.setSuffix(_translate("MainWindow", "%"))
        self.label_3.setToolTip(_translate("MainWindow", "This value is calculated automatically. If you believe it is incorrect, you can set your own value and press enter to replot"))
        self.label_3.setStatusTip(_translate("MainWindow", "This value is calculated automatically. If you believe it is incorrect, you can set your own value and press enter to replot"))
        self.label_3.setText(_translate("MainWindow", "Field Resolution"))
        self.spinBox_resolution.setToolTip(_translate("MainWindow", "This value is calculated automatically. If you believe it is incorrect, you can set your own value and press enter to replot"))
        self.spinBox_resolution.setStatusTip(_translate("MainWindow", "This value is calculated automatically. If you believe it is incorrect, you can set your own value and press enter to replot"))
        self.spinBox_resolution.setSuffix(_translate("MainWindow", " pixels"))
        self.label.setText(_translate("MainWindow", "Well"))
        self.pushButton_done.setText(_translate("MainWindow", "Done"))
        self.label_4.setText(_translate("MainWindow", "Color"))

from .mplwidget import MplWidget
