[tool.poetry]
name = "udp-filetransfer"
version = "0.1.0"
description = "Reliable filetransfer over UDP"
authors = ["golyalpha <golyalpha@gmail.com>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = "^3.7"
tqdm = "^4.31"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
pylint = "^2.3"
rope = "^0.12.0"
nuitka = "^0.6.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
