[tool.poetry]
name = "po.simple_test"
version = "0.2.0"
description = "A simple test runner"
authors = ["Philip Olson <philip.olson@pm.me>"]
license = "WTFNMFPL-1.0"
readme = "README.md"
repository = "https://github.com/olsonpm/py_simple-test"
include = ["license.txt"]
packages = [
  { include = "po" }
]

[tool.poetry.scripts]
simple-test = "po.simple_test.script:main"

[tool.poetry.dependencies]
python = "^3.7"
wrapt = "^1.10"
ordered_set = "^3.1"
case_conversion = "^2.1"
tedent = "^0.1.1"
simple_test_process = "^0.2.0"
simple_test_default_reporter = "^0.2.0"

[tool.poetry.dev-dependencies]
num2words = "^0.5.8"
simple_chalk = "^0.1.0"
pretty_simple_namespace = "^0.1.0"
toml = "^0.10.0"
is_git_repo_clean = "^0.3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
