
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-11T10:14:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "934b9f18454aad192f2248771d2992b992e84e80",
 "version": "1.8.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
