- project:
    templates:
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
    check:
      jobs:
        - virtualbmc-tempest-ironic-ipmi-iscsi
        - virtualbmc-tempest-ironic-ipmi-iscsi-python2
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - virtualbmc-tempest-ironic-ipmi-iscsi
        - virtualbmc-tempest-ironic-ipmi-iscsi-python2
        - openstack-tox-lower-constraints
