# Generated by Django 2.1.4 on 2019-03-24 06:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0005_auto_20190321_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('visible_code', models.CharField(max_length=14)),
                ('payment_method', models.CharField(max_length=12)),
                ('status', models.IntegerField(choices=[(10, 'New: pending send to gateway'), (20, 'Pending: Awaiting gateway response'), (30, 'Success: pending POST to Salebox'), (31, 'Success: successfully POSTed to Salebox'), (40, 'Rejected: gateway rejected payment'), (50, 'Timeout: gateway did not respond in an acceptable time period')])),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutStoreUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(10, 'New: pending send to gateway'), (20, 'Pending: Awaiting gateway response'), (30, 'Success: pending POST to Salebox'), (31, 'Success: successfully POSTed to Salebox'), (40, 'Rejected: gateway rejected payment'), (50, 'Timeout: gateway did not respond in an acceptable time period')])),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleboxdjango.CheckoutStore')),
            ],
        ),
    ]
