# Generated by Django 2.1.4 on 2019-03-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0006_checkoutstore_checkoutstoreupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='name_sorted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkoutstore',
            name='visible_code',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
