# Generated by Django 2.1.4 on 2019-03-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0006_checkoutstore_checkoutstoreupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutstore',
            name='visible_code',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['bestseller_rank', 'name'], name='saleboxdjan_bestsel_f7b707_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['-bestseller_rank', 'name'], name='saleboxdjan_bestsel_54c126_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sale_price', 'name'], name='saleboxdjan_sale_pr_21a4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['-sale_price', 'name'], name='saleboxdjan_sale_pr_feafc6_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['rating_score', 'name'], name='saleboxdjan_rating__8cb616_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['-rating_score', 'name'], name='saleboxdjan_rating__b209b4_idx'),
        ),
    ]
