#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='smx',
      version='0.8',
      description='Simple python macro expansion',
      author='Erik Aronesty',
      author_email='erik@q32.com',
      url='https://github.com/earonesty/python-smx',
      py_modules=['smx'],
     )
