# DO NOT EDIT THIS FILE!
#
# Python module SDOPackage generated by omniidl

import omniORB
omniORB.updateModule("rtctree.rtc.SDOPackage")

# ** 1. Stub files contributing to this module
import rtctree.rtc.SDOPackage_idl

# ** 2. Sub-modules

# ** 3. End
