#!/bin/bash

if markdown-pp --help 2>/dev/null >/dev/null ; then

    MSG='[](!!!!!! DO NOT EDIT THIS FILE !!! RUN update_readme.sh TO UPDATE THIS FILE !!!!!!!!)'
    echo $MSG > README.md
    echo $MSG >> README.md
    echo $MSG >> README.md
    echo >> README.md

    (cd docs; markdown-pp README.mdd) >> README.md

    echo >> README.md
    echo $MSG >> README.md
    echo $MSG >> README.md
    echo $MSG >> README.md

    echo please run \"git diff\" to see the changes
else
    echo
    echo please run \"pip install -r docs/requirements.txt first\"
fi
