
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4228176a4dfe844442f42fa92b891161b549eca4",
 "version": "0.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
