
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-08T13:56:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "988d054842d9fa078f201810fc0b4cc193efbc51",
 "version": "v0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
