import sys

versions = ["KJV"]

chaps = {
    "Genesis": 50,
    "Exodus": 40,
    "Leviticus": 27,
    "Numbers": 36,
    "Deuteronomy": 34,
    "Joshua": 24,
    "Judges": 21,
    "Ruth": 4,
    "1 Samuel": 31,
    "2 Samuel": 24,
    "1 Kings": 22,
    "2 Kings": 25,
    "1 Chronicles": 29,
    "2 Chronicles": 36,
    "Ezra": 10,
    "Nehemiah": 13,
    "Esther": 10,
    "Job": 42,
    "Psalms": 150,
    "Proverbs": 31,
    "Ecclesiastes": 12,
    "Song of Solomon": 8,
    "Isaiah": 66,
    "Jeremiah": 52,
    "Lamentations": 5,
    "Ezekiel": 48,
    "Daniel": 12,
    "Hosea": 14,
    "Joel": 3,
    "Amos": 9,
    "Obadiah": 1,
    "Jonah": 4,
    "Micah": 7,
    "Nahum": 3,
    "Habakkuk": 3,
    "Zephaniah": 3,
    "Haggai": 2,
    "Zechariah": 14,
    "Malachi": 4,
    "Matthew": 28,
    "Mark": 16,
    "Luke": 24,
    "John": 21,
    "Acts": 28,
    "Romans": 16,
    "1 Corinthians": 16,
    "2 Corinthians": 13,
    "Galatians": 6,
    "Ephesians": 6,
    "Philippians": 4,
    "Colossians": 4,
    "1 Thessalonians": 5,
    "2 Thessalonians": 3,
    "1 Timothy": 6,
    "2 Timothy": 4,
    "Titus": 3,
    "Philemon": 1,
    "Hebrews": 13,
    "James": 5,
    "1 Peter": 5,
    "2 Peter": 3,
    "1 John": 5,
    "2 John": 1,
    "3 John": 1,
    "Jude": 1,
    "Revelation": 22
}

class NIV:

    books = [
        "Genesis",
        "Exodus",
        "Numbers",
        "Deuteronomy",
        "Joshua",
        "Judges",
        "Ruth",
        "1 Samuel",
        "2 Samuel",
        "1 Kings",
        "2 Kings",
        "1 Chronicles",
        "2 Chronicles",
        "Ezra",
        "Nehemiah",
        "Esther",
        "Job",
        "Psalms",
        "Proverbs",
        "Ecclesiastes",
        "Song of Solomon",
        "Isaiah",
        "Jeremiah",
        "Lamentations",
        "Ezekiel",
        "Daniel",
        "Hosea",
        "Joel",
        "Amos",
        "Obadiah",
        "Jonah",
        "Micah",
        "Nahum",
        "Habakkuk",
        "Zephaniah",
        "Haggai",
        "Zechariah",
        "Malachi",
        "Matthew",
        "Mark",
        "Luke",
        "John",
        "Acts",
        "Romans",
        "1 Corinthians",
        "2 Corinthians",
        "Galatians",
        "Ephesians",
        "Philippians",
        "Colossians",
        "1 Thessalonians",
        "2 Thessalonians",
        "1 Timothy",
        "2 Timothy",
        "Titus",
        "Philemon",
        "Hebrews",
        "James",
        "1 Peter",
        "2 Peter",
        "1 John",
        "2 John",
        "3 John",
        "Jude",
        "Revelation"
    ]


class KJV:
    
    def GetDAT():
        exe = sys.exec_prefix
        fullpath = exe + "\Lib\site-packages\locallib\kjvdat.txt"
        return fullpath
        

    books = {
        "Genesis": "Gen",
        "Exodus": "Exo",
        "Leviticus": "Lev",
        "Numbers": "Num",
        "Deuteronomy": "Deu",
        "Joshua": "Jos",
        "Judges": "Jdg",
        "Ruth": "Rut",
        "1 Samuel": "Sa1",
        "2 Samuel": "Sa2",
        "1 Kings": "Kg1",
        "2 Kings": "Kg2",
        "1 Chronicles": "Ch1",
        "2 Chronicles": "Ch2",
        "Ezra": "Ezr",
        "Nehemiah": "Neh",
        "Esther": "Est",
        "Job": "Job",
        "Psalms": "Psa",
        "Proverbs": "Pro",
        "Ecclesiastes": "Ecc",
        "Song of Solomon": "Sol",
        "Isaiah": "Isa",
        "Jeremiah": "Jer",
        "Lamentations": "Lam",
        "Ezekiel": "Eze",
        "Daniel": "Dan",
        "Hosea": "Hos",
        "Joel": "Joe",
        "Amos": "Amo",
        "Obadiah": "Oba",
        "Jonah": "Jon",
        "Micah": "Mic",
        "Nahum": "Nah",
        "Habakkuk": "Hab",
        "Zephaniah": "Zep",
        "Haggai": "Hag",
        "Zechariah": "Zac",
        "Malachi": "Mal",
        "Matthew": "Mat",
        "Mark": "Mar",
        "Luke": "Luk",
        "John": "Joh",
        "Acts": "Act",
        "Romans": "Rom",
        "1 Corinthians": "Co1",
        "2 Corinthians": "Co2",
        "Galatians": "Gal",
        "Ephesians": "Eph",
        "Philippians": "Phi",
        "Colossians": "Col",
        "1 Thessalonians": "Th1",
        "2 Thessalonians": "Th2",
        "1 Timothy": "Ti1",
        "2 Timothy": "Ti2",
        "Titus": "Tit",
        "Philemon": "Phm",
        "Hebrews": "Heb",
        "James": "Jam",
        "1 Peter": "Pe1",
        "2 Peter": "Pe2",
        "1 John": "Jo1",
        "2 John": "Jo2",
        "3 John": "Jo3",
        "Jude": "Jde",
        "Revelation": "Rev"
    }
