[tool.poetry]
name = "aiohypixel"
version = "0.1.0"
description = "An asynchronous Hypixel API Wrapper written in Python"
authors = ["Tmpod"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.5"
dataclasses = "^0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
