# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangopayments', '0010_auto_20171206_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangopaybankaccount',
            name='account_type',
            field=models.CharField(choices=[(b'IBAN', 'IBAN'), (b'US', 'US'), (b'OTHER', 'Other')], default=b'IBAN', max_length=5),
        ),
    ]
