# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangopayments', '0013_mangopaytransfer_result_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangopaypayout',
            name='result_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='mangopaypayout',
            name='result_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
