# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangopayments', '0017_auto_20171215_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangopaybankaccount',
            name='account_type',
            field=models.CharField(choices=[(b'BI', 'IBAN'), (b'US', 'US'), (b'O', 'Other')], default=b'BI', max_length=5),
        ),
    ]
