# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangopayments', '0020_auto_20171222_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangopaydocument',
            name='status',
            field=models.CharField(blank=True, choices=[(b'CREATED', b'CREATED'), (b'VALIDATION_ASKED', b'VALIDATION_ASKED'), (b'VALIDATED', b'VALIDATED'), (b'REFUSED', b'REFUSED')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mangopaydocument',
            name='type',
            field=models.CharField(choices=[(b'IDENTITY_PROOF', b'IDENTITY_PROOF'), (b'REGISTRATION_PROOF', b'REGISTRATION_PROOF'), (b'ARTICLES_OF_ASSOCIATION', b'ARTICLES_OF_ASSOCIATION'), (b'SHAREHOLDER_DECLARATION', b'SHAREHOLDER_DECLARATION'), (b'ADDRESS_PROOF', b'ADDRESS_PROOF')], max_length=25),
        ),
    ]
