# Generated by Django 2.1.5 on 2019-03-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('font_icons', '0002_fonticonmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonticonmodel',
            name='style',
            field=models.CharField(choices=[('fa', 'Font Awesome (classic)'), ('fas', 'Font Awesome Solid'), ('far', 'Font Awesome Regular (Partial Pro)'), ('fal', 'Font Awesome Light (Pro)'), ('fab', 'Font Awesome Brands')], default='fas', max_length=6),
        ),
    ]
