# Generated by Django 2.1.5 on 2019-03-13 22:13

from django.db import migrations, models
import django.db.models.deletion
import django_datetime_elapsed_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Python module')),
                ('class_name', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Python class')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Python module')),
                ('class_name', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Python class')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('todo', models.BooleanField(blank=True, default=False, null=True, verbose_name='TODO')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', django_datetime_elapsed_field.DateTimeElapsedField(auto_now_add=True)),
                ('updated_at', django_datetime_elapsed_field.DateTimeElapsedField(blank=True, editable=False, null=True)),
                ('completed_at', django_datetime_elapsed_field.DateTimeElapsedField(blank=True, editable=False, null=True)),
                ('reminded_at', django_datetime_elapsed_field.DateTimeElapsedField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Category', verbose_name='Category')),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
