
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-22T12:32:45-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f45679c81721bf60fb8cf582d944219ca88737a",
 "version": "V1.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
