# we want to make sure it is run on trusty where sudo is provided for postgres
dist: trusty
language: python
sudo: true
python:
  - "3.6"
sudo: required
env:
  - DATABASE=DUMMY

services:
  - docker

cache:
  directories:
    - eggs
install:
  - sudo mv /etc/boto.cfg /etc/boto.cfg.bak
  - pip install -e .[test]
  - pip install flake8 codecov pytest-cov
before_script:
  - docker run --rm -d -p 19000:9000 --name minio -e MINIO_ACCESS_KEY=xxxxxxxxxx -e MINIO_SECRET_KEY=xxxxxxxxxx minio/minio server /data
  - sleep 5
script:
  - flake8 guillotina_s3storage --config=setup.cfg
  - pytest -s --cov=guillotina_s3storage -s --tb=native -v --cov-report term-missing --cov-append ./guillotina_s3storage
after_success:
  - sudo mv /etc/boto.cfg.bak /etc/boto.cfg
  - codecov
