""" error module """

ERROR_OK = 0

ERROR_WRONG_MODE = -3
ERROR_WRONG_NOTE_FILE_CONTEXT = -4

ERROR_NO_CONFIG_FILE = -8
ERROR_NO_ROOT_NOTE = -9
ERROR_NO_META_FILE = -10
ERROR_NO_CONTENT_FILE = -11
ERROR_NO_TAG_FILE = -12

ERROR_META_FILE_ALREADY_EXISTS = -20

ERROR_INVALID_INDEX = -13

ERROR_SEARCH_NOTE_AMBIGUITY = -30
