
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-21T21:59:23+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc2d006ecb824ef4e1a6b8c35d703fa559a9a2ca",
 "version": "v0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
