[tool.poetry]
name = "py-ax-s"
version = "0.1.1"
description = "A Python client for the ax-s API."
authors = ["elliott-maguire <elliott.maguire@ax-s.io>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.21"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pylint = "^2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
