[tool.poetry]
name = "dtc"
version = "0.1.0"
description = "Generate Dataclass without writting them !"
authors = ["jgirardet <ijkl@netc.fr>"]
keywwords = ["dataclass", "dataclasses", "json", "generator"]
classifiers = [
	"Programming Language :: Python :: 3.7",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.6"
reorder-python-imports = "^1.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
