[tool.poetry]
name = "cc-agency"
version = "6.1.2"
authors = ["Christoph Jansen <Christoph.Jansen@htw-berlin.de>", "Bruno Schilling <Bruno.Schilling@student.htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/cc-agency"
homepage = "https://www.curious-containers.cc/"
description = "CC-Agency is part of the Curious Containers project. It connects to a cluster of docker-engines for the distributed execution of reproducible data-driven experiments defined in RED format."

[tool.poetry.dependencies]
python = "^3.4"
cc-core = "~6.1"
flask = "^1.0"
jsonschema = "^2.6"
docker = "^3.4"
pyzmq = "^17.0"
"ruamel.yaml" = "^0.15"
pymongo = "^3.7"
cryptography = "^2.2"
requests = "^2.18"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
ccagency-controller = 'cc_agency.controller.main:main'
ccagency = 'cc_agency.tools.main:main'
