
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-15T12:42:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "16c5e267a4bd15cc52e9f3b541665088a228024a",
 "version": "2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
