[tool.poetry]
name = "mailgun-cli"
version = "0.1.5"
description = "mailgun cli, forwarding mail"
authors = ["Nutchanon Ninyawee  <dev@nutchanon.org>"]

[tool.poetry.scripts]
mailgun = 'mailgun_cli.cli:main'

[tool.poetry.dependencies]
python = "^3.7"
uplink = "^0.8.0"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
