---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "benji.fullname" . }}
data:
  benji.yaml: |
    {{ .Values.benji.configuration | toYaml | nindent 4 }}
  crontab: |
    {{ .Values.benji.crontab | nindent 4 }}
