[tool.poetry]
name = "tx"
version = "0.0.2"
description = "An extension base for twisted based projects"
authors = ["Yehuda Deutsch <yeh@uda.co.il>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
Twisted = "^18.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
