# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-03-07T16:28:54.568976'

__version__ = '2019.3.1'
__sha__ = '69fe6b584a09f104e503797fd50701fabec44cd2'
__revision__ = '69fe6b584a09f104e503797fd50701fabec44cd2'
