/* Generated by Nim Compiler v0.19.9 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <time.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw;
typedef struct tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ;
typedef struct tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_JfHvHzMrhKkWAUvQKe0i1A tyTuple_JfHvHzMrhKkWAUvQKe0i1A;
typedef struct tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashdotdotslashusrslashlibslashnimslashpureslashtimesdotnim__diB2NTuAIWY0FO9c5IUJRGg tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashdotdotslashusrslashlibslashnimslashpureslashtimesdotnim__diB2NTuAIWY0FO9c5IUJRGg;
typedef struct RootObj RootObj;
#  define nimfr_(proc, file) \
    TFrame FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#  define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

#  define nimln_(n, file) \
    FR_.line = n; FR_.filename = file;
struct tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q {
NI64 seconds;
NI nanosecond;
};
struct tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ {
tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q time;
NI utcOffset;
NIM_BOOL isDst;
};
typedef struct {
N_NIMCALL_PTR(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, ClP_0) (tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q x, void* ClE_0);
void* ClE_0;
} tyProc_bs1dgeTxHIjPGTR9axkkHbg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw {
tyProc_bs1dgeTxHIjPGTR9axkkHbg zonedTimeFromTimeImpl;
tyProc_bs1dgeTxHIjPGTR9axkkHbg zonedTimeFromAdjTimeImpl;
NimStringDesc* name;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct tyTuple_JfHvHzMrhKkWAUvQKe0i1A {
void* Field0;
tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashdotdotslashusrslashlibslashnimslashpureslashtimesdotnim__diB2NTuAIWY0FO9c5IUJRGg* Field1;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashdotdotslashusrslashlibslashnimslashpureslashtimesdotnim__diB2NTuAIWY0FO9c5IUJRGg {
  RootObj Sup;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
static N_NIMCALL(void, Marker_tyRef_HsJiUUcO9cHBdUCi0HwkSTA)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_9a5v4OQPlGqsA25ioN8hFYA)(void* p, NI op);
static N_NIMCALL(void, TM_6NbDwwj5FY059b1gz2AsAZQ_4)(void);
N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, TM_6NbDwwj5FY059b1gz2AsAZQ_5)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached_mMRdr4sgmnykA9aWeM9aDZlw_2)(void);
tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* utcInstance_oeKVHn4dFpBJO35HhEkelw;
TNimType NTI_F8OvqlxXyGXRSiK9c1fCDVw_;
TNimType NTI_bs1dgeTxHIjPGTR9axkkHbg_;
TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_ytyiCJqK439aF9cIibuRVpAg_;
TNimType NTI_diB2NTuAIWY0FO9c5IUJRGg_;
TNimType NTI_HsJiUUcO9cHBdUCi0HwkSTA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_9a5v4OQPlGqsA25ioN8hFYA_;
tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* localInstance_cLtN9cK9bCe6IPhJ3UFNLNKA;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
static N_NIMCALL(void, Marker_tyRef_HsJiUUcO9cHBdUCi0HwkSTA)(void* p, NI op) {
	tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashdotdotslashusrslashlibslashnimslashpureslashtimesdotnim__diB2NTuAIWY0FO9c5IUJRGg* a;
	a = (tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashdotdotslashusrslashlibslashnimslashpureslashtimesdotnim__diB2NTuAIWY0FO9c5IUJRGg*)p;
}
static N_NIMCALL(void, Marker_tyRef_9a5v4OQPlGqsA25ioN8hFYA)(void* p, NI op) {
	tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* a;
	a = (tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*)p;
	nimGCvisit((void*)(*a).zonedTimeFromTimeImpl.ClE_0, op);
	nimGCvisit((void*)(*a).zonedTimeFromAdjTimeImpl.ClE_0, op);
	nimGCvisit((void*)(*a).name, op);
}
static N_NIMCALL(void, TM_6NbDwwj5FY059b1gz2AsAZQ_4)(void) {
	nimGCvisit((void*)utcInstance_oeKVHn4dFpBJO35HhEkelw, 0);
}
static N_NIMCALL(void, TM_6NbDwwj5FY059b1gz2AsAZQ_5)(void) {
	nimGCvisit((void*)localInstance_cLtN9cK9bCe6IPhJ3UFNLNKA, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
		callDepthLimitReached_mMRdr4sgmnykA9aWeM9aDZlw_2();
	}
	LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesInit000)(void) {
{

	nimRegisterThreadLocalMarker(TM_6NbDwwj5FY059b1gz2AsAZQ_4);


	nimRegisterThreadLocalMarker(TM_6NbDwwj5FY059b1gz2AsAZQ_5);

	tzset();
}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesDatInit000)(void) {
static TNimNode* TM_6NbDwwj5FY059b1gz2AsAZQ_2_3[3];
static TNimNode* TM_6NbDwwj5FY059b1gz2AsAZQ_3_2[2];
static TNimNode TM_6NbDwwj5FY059b1gz2AsAZQ_0[8];
NTI_F8OvqlxXyGXRSiK9c1fCDVw_.size = sizeof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw);
NTI_F8OvqlxXyGXRSiK9c1fCDVw_.kind = 18;
NTI_F8OvqlxXyGXRSiK9c1fCDVw_.base = 0;
TM_6NbDwwj5FY059b1gz2AsAZQ_2_3[0] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[1];
NTI_bs1dgeTxHIjPGTR9axkkHbg_.size = sizeof(tyTuple_JfHvHzMrhKkWAUvQKe0i1A);
NTI_bs1dgeTxHIjPGTR9axkkHbg_.kind = 18;
NTI_bs1dgeTxHIjPGTR9axkkHbg_.base = 0;
TM_6NbDwwj5FY059b1gz2AsAZQ_3_2[0] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[3];
NTI_vr5DoT1jILTGdRlYv1OYpw_.size = sizeof(void*);
NTI_vr5DoT1jILTGdRlYv1OYpw_.kind = 26;
NTI_vr5DoT1jILTGdRlYv1OYpw_.base = 0;
NTI_vr5DoT1jILTGdRlYv1OYpw_.flags = 3;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[3].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[3].offset = offsetof(tyTuple_JfHvHzMrhKkWAUvQKe0i1A, Field0);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[3].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[3].name = "Field0";
TM_6NbDwwj5FY059b1gz2AsAZQ_3_2[1] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[4];
NTI_diB2NTuAIWY0FO9c5IUJRGg_.size = sizeof(tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashdotdotslashusrslashlibslashnimslashpureslashtimesdotnim__diB2NTuAIWY0FO9c5IUJRGg);
NTI_diB2NTuAIWY0FO9c5IUJRGg_.kind = 17;
NTI_diB2NTuAIWY0FO9c5IUJRGg_.base = (&NTI_ytyiCJqK439aF9cIibuRVpAg_);
NTI_diB2NTuAIWY0FO9c5IUJRGg_.flags = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[5].len = 0; TM_6NbDwwj5FY059b1gz2AsAZQ_0[5].kind = 2;
NTI_diB2NTuAIWY0FO9c5IUJRGg_.node = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[5];
NTI_HsJiUUcO9cHBdUCi0HwkSTA_.size = sizeof(tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashdotdotslashusrslashlibslashnimslashpureslashtimesdotnim__diB2NTuAIWY0FO9c5IUJRGg*);
NTI_HsJiUUcO9cHBdUCi0HwkSTA_.kind = 22;
NTI_HsJiUUcO9cHBdUCi0HwkSTA_.base = (&NTI_diB2NTuAIWY0FO9c5IUJRGg_);
NTI_HsJiUUcO9cHBdUCi0HwkSTA_.marker = Marker_tyRef_HsJiUUcO9cHBdUCi0HwkSTA;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[4].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[4].offset = offsetof(tyTuple_JfHvHzMrhKkWAUvQKe0i1A, Field1);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[4].typ = (&NTI_HsJiUUcO9cHBdUCi0HwkSTA_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[4].name = "Field1";
TM_6NbDwwj5FY059b1gz2AsAZQ_0[2].len = 2; TM_6NbDwwj5FY059b1gz2AsAZQ_0[2].kind = 2; TM_6NbDwwj5FY059b1gz2AsAZQ_0[2].sons = &TM_6NbDwwj5FY059b1gz2AsAZQ_3_2[0];
NTI_bs1dgeTxHIjPGTR9axkkHbg_.node = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[2];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[1].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[1].offset = offsetof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw, zonedTimeFromTimeImpl);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[1].typ = (&NTI_bs1dgeTxHIjPGTR9axkkHbg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[1].name = "zonedTimeFromTimeImpl";
TM_6NbDwwj5FY059b1gz2AsAZQ_2_3[1] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[6];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[6].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[6].offset = offsetof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw, zonedTimeFromAdjTimeImpl);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[6].typ = (&NTI_bs1dgeTxHIjPGTR9axkkHbg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[6].name = "zonedTimeFromAdjTimeImpl";
TM_6NbDwwj5FY059b1gz2AsAZQ_2_3[2] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[7];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[7].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[7].offset = offsetof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw, name);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[7].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[7].name = "name";
TM_6NbDwwj5FY059b1gz2AsAZQ_0[0].len = 3; TM_6NbDwwj5FY059b1gz2AsAZQ_0[0].kind = 2; TM_6NbDwwj5FY059b1gz2AsAZQ_0[0].sons = &TM_6NbDwwj5FY059b1gz2AsAZQ_2_3[0];
NTI_F8OvqlxXyGXRSiK9c1fCDVw_.node = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[0];
NTI_9a5v4OQPlGqsA25ioN8hFYA_.size = sizeof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*);
NTI_9a5v4OQPlGqsA25ioN8hFYA_.kind = 22;
NTI_9a5v4OQPlGqsA25ioN8hFYA_.base = (&NTI_F8OvqlxXyGXRSiK9c1fCDVw_);
NTI_9a5v4OQPlGqsA25ioN8hFYA_.marker = Marker_tyRef_9a5v4OQPlGqsA25ioN8hFYA;
}

