
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-11T12:53:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "33ae99f1e2ca0b54b27c89098ba9a3d37b26e524",
 "version": "1.8.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
