
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-10T17:35:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "127949619e2102f004eac3a66a919fdfabe4de22",
 "version": "0.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
