# we want to make sure it is run on trusty where sudo is provided for postgres
dist: trusty
language: python
python:
    - "3.6"
addons:
  postgresql: 9.6
sudo: required
env:
  - DATABASE=DUMMY
  - DATABASE=postgres
cache:
  directories:
    - eggs
services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database guillotina;' -U postgres
install:
  - pip install -e .[test]
  - pip install flake8 codecov
  - sleep 5
script:
  - flake8 guillotina_batch --config=setup.cfg
  - pytest -s --cov=guillotina_batch -s --tb=native -v --cov-report term-missing --cov-append guillotina_batch
after_success:
  - codecov
