- job:
    name: ara-tox-py3
    parent: tox
    nodeset: ubuntu-bionic
    vars:
      tox_envlist: py3

- job:
    name: ara-tox-linters
    parent: tox
    nodeset: ubuntu-bionic
    vars:
      tox_envlist: linters

- job:
    name: ara-1.0-integration-base
    parent: base
    vars:
      integration_ansible_name: "{{ ansible_user_dir }}/src/github.com/ansible/ansible"
      integration_ansible_version: null
    run: playbooks/integration-tests.yaml
    post-run: tests/integration-post.yaml

- job:
    name: ara-1.0-integration-fedora-devel
    parent: ara-integration-base
    nodeset: fedora-latest
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: devel

- job:
    name: ara-1.0-integration-fedora-2.7
    parent: ara-1.0-integration-base
    nodeset: fedora-latest
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.7

- job:
    name: ara-1.0-integration-ubuntu-2.6
    parent: ara-1.0-integration-base
    nodeset: ubuntu-bionic
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.6

- job:
    name: ara-1.0-role-integration-base
    parent: base
    files:
      - ara/*
      - playbooks/*
      - roles/*
      - tests/*
      - .zuul.d/*
      - setup.py
      - setup.cfg
      - requirements.txt
      - test-requirements.txt
    pre-run: tests/role-integration-pre.yaml
    run: playbooks/ara_api.yaml
    vars:
      ara_api_source: "{{ ansible_user_dir }}/src/git.openstack.org/openstack/ara"
      ara_api_web_server: nginx
      ara_api_wsgi_server: gunicorn
      ansible_python_interpreter: /usr/bin/python3

- job:
    name: ara-1.0-role-integration-ubuntu
    parent: ara-1.0-role-integration-base
    nodeset: ubuntu-bionic

- job:
    name: ara-1.0-role-integration-fedora
    parent: ara-1.0-role-integration-base
    nodeset: fedora-latest

- job:
    name: ara-web-role-integration-base
    parent: base
    vars:
      ara_web_source: "{{ ansible_user_dir }}/src/git.openstack.org/openstack/ara-web"
      ara_web_api_server: "https://api.demo.recordsansible.org"
    files:
      - playbooks/*
      - roles/ara_frontend_nginx/*
      - roles/ara_web/*
      - src/.*
      - public/.*
      - package.json
      - package-lock.json
      - .zuul.d/*
    required-projects:
      - openstack/ara-web
      - openstack/ara-infra
    run: playbooks/ara_web.yaml
    post-run: tests/role-ara-web-post.yaml

- job:
    name: ara-web-role-integration-ubuntu
    parent: ara-web-role-integration-base
    nodeset: ubuntu-bionic

- job:
    name: ara-web-role-integration-fedora
    parent: ara-web-role-integration-base
    nodeset: fedora-latest

- project:
    vars:
      rtd_webhook_id: '49230'
    templates:
      - docs-on-readthedocs
    check:
      jobs:
        - ara-1.0-integration-fedora-2.7
        - ara-1.0-integration-fedora-devel:
            voting: false
        - ara-1.0-integration-ubuntu-2.6
        - ara-1.0-role-integration-ubuntu
        - ara-1.0-role-integration-fedora
        - ara-web-role-integration-ubuntu
        - ara-web-role-integration-fedora
        - ara-tox-linters
        - ara-tox-py3
    gate:
      jobs:
        - ara-1.0-integration-fedora-2.7
        - ara-1.0-integration-ubuntu-2.6
        - ara-1.0-role-integration-ubuntu
        - ara-1.0-role-integration-fedora
        - ara-web-role-integration-ubuntu
        - ara-web-role-integration-fedora
        - ara-tox-linters
        - ara-tox-py3
