
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-08T15:01:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb7dec45d5bafdf15178d72db32bbb458447756d",
 "version": "1.8.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
