#ifndef COMPADRE_CONFIG_H
#define COMPADRE_CONFIG_H

#define COMPADRE_DEBUG
#define COMPADRE_USE_KOKKOSCORE
#define COMPADRE_USE_LAPACK
#define COMPADRE_USE_OPENBLAS
#define COMPADRE_USE_OPENMP
#define COMPADRE_USE_PYTHON
#define LAPACK_DECLARED_THREADSAFE
#define COMPADRE_VERSION_MAJOR 1
#define COMPADRE_VERSION_MINOR 0
#define COMPADRE_VERSION_PATCH 1
#define COMPADRE_SEMVER "1.0.1-sha.137ed89+1011101101"
#define COMPADRE_COMMIT "137ed891deae1d0a0a3ae0929c38972dc7ed6ba1"
#define COMPADRE_CXX_FLAGS " -fopenmp "
#define COMPADRE_CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX:BOOL=\"/usr/local\" -DPYTHON_CALLING_BUILD:BOOL=\"ON\" -DCompadre_USE_MPI:BOOL=\"OFF\" -DCompadre_USE_PYTHON:BOOL=\"ON\" -DCompadre_USE_MATLAB:BOOL=\"ON\" -DCompadre_EXAMPLES:BOOL=\"OFF\""
#define GMLS_MODULE_DEST "lib/python/dist-packages"
#define COMPADRE_INSTALL_PREFIX "/usr/local"

#endif
