- job:
    name: rally-task-at-devstack
    parent: devstack
    description: Base job for launching Rally task at Devstack
    required-projects:
      - name: openstack-dev/devstack
      - name: openstack-infra/devstack-gate
      - name: openstack/rally-openstack
      # NOTE(andreykurilin): it is a required project to fetch the latest
      #   version and test master of rally-openstack with master of rally
      - name: openstack/rally
    timeout: 7200
    roles:
      - zuul: openstack-dev/devstack
    vars:
      devstack_plugins:
        rally-openstack: https://git.openstack.org/openstack/rally-openstack
    run: tests/ci/playbooks/run-rally-task.yaml
    post-run: tests/ci/playbooks/post-rally-task.yaml
