[tool.towncrier]
package = "trio_ari"
filename = "docs/source/history.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/M-o-a-T/trio-ari/issues/{issue}>`__"
