
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-06T03:08:44-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "306c61e1efedac7b368dee8fd2b644f95716e608",
 "version": "v0.4.46"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
