# Generated by Django 2.1.5 on 2019-01-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_framework', '0003_auto_20190126_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitymetadata',
            name='metadata_url',
            field=models.URLField(blank=True, help_text='Changing this value will override the xml file.'),
        ),
        migrations.AlterField(
            model_name='servicemetadata',
            name='metadata_url',
            field=models.URLField(blank=True, help_text='Changing this value will override the xml file.'),
        ),
    ]
