# Generated by Django 2.1.5 on 2019-01-28 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_framework', '0005_auto_20190126_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='cert_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='key_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='name_id_format',
            field=models.CharField(choices=[('Email Address', 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'), ('Unspecified', 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified')], default='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', max_length=200),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='valid_for',
            field=models.DurationField(blank=True, default=datetime.timedelta(365)),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='cert_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='key_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='name_id_format',
            field=models.CharField(choices=[('Email Address', 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'), ('Unspecified', 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified')], default='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='valid_for',
            field=models.DurationField(blank=True, default=datetime.timedelta(365)),
        ),
    ]
