# Generated by Django 2.1.5 on 2019-01-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_framework', '0006_auto_20190128_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='name_id_format',
            field=models.CharField(choices=[('urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', 'Email Address'), ('urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified', 'Unspecified')], default='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name_id_format',
            field=models.CharField(choices=[('urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', 'Email Address'), ('urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified', 'Unspecified')], default='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', max_length=200),
        ),
    ]
