# Generated by Django 2.1.5 on 2019-02-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_framework', '0009_serviceprovider_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='logout_requests_signed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='sign_assertion',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='sign_response',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='authn_requests_signed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='logout_requests_signed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='want_assertions_signed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='want_response_signed',
            field=models.NullBooleanField(),
        ),
    ]
