# Generated by Django 2.1.5 on 2019-02-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_framework', '0010_auto_20190205_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value_path', models.CharField(max_length=100)),
                ('identity_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_saml2_framework.IdentityProvider')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value_path', models.CharField(max_length=100)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_saml2_framework.ServiceProvider')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='serviceattribute',
            unique_together={('service_provider', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='identityattribute',
            unique_together={('identity_provider', 'name')},
        ),
    ]
