# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkMeshFileWriterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkMeshFileWriterPython', [dirname(__file__)])
        except ImportError:
            import _itkMeshFileWriterPython
            return _itkMeshFileWriterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkMeshFileWriterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkMeshFileWriterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkMeshFileWriterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import ITKCommonBasePython
import pyBasePython
import itkMeshBasePython
import itkArrayPython
import vnl_vectorPython
import vnl_matrixPython
import stdcomplexPython
import itkPointSetPython
import itkVectorContainerPython
import itkVectorPython
import vnl_vector_refPython
import itkFixedArrayPython
import itkOffsetPython
import itkSizePython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkCovariantVectorPython
import itkPointPython
import itkContinuousIndexPython
import itkIndexPython
import itkMapContainerPython
import itkBoundingBoxPython
import itkMeshIOBasePython

def itkMeshFileWriterMD3DTD33DD_New():
  return itkMeshFileWriterMD3DTD33DD.New()


def itkMeshFileWriterMD3STD33DD_New():
  return itkMeshFileWriterMD3STD33DD.New()


def itkMeshFileWriterMF3DTF33FF_New():
  return itkMeshFileWriterMF3DTF33FF.New()


def itkMeshFileWriterMF3STF33FF_New():
  return itkMeshFileWriterMF3STF33FF.New()


def itkMeshFileWriterMD2DTD22DD_New():
  return itkMeshFileWriterMD2DTD22DD.New()


def itkMeshFileWriterMD2STD22DD_New():
  return itkMeshFileWriterMD2STD22DD.New()


def itkMeshFileWriterMF2DTF22FF_New():
  return itkMeshFileWriterMF2DTF22FF.New()


def itkMeshFileWriterMF2STF22FF_New():
  return itkMeshFileWriterMF2STF22FF.New()

class itkMeshFileWriterMD2DTD22DD(ITKCommonBasePython.itkProcessObject):
    """Proxy of C++ itkMeshFileWriterMD2DTD22DD class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMeshFileWriterMD2DTD22DD_Pointer":
        """__New_orig__() -> itkMeshFileWriterMD2DTD22DD_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMeshFileWriterMD2DTD22DD_Pointer":
        """Clone(itkMeshFileWriterMD2DTD22DD self) -> itkMeshFileWriterMD2DTD22DD_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_Clone(self)


    def SetInput(self, input: 'itkMeshD2DTD22DD') -> "void":
        """SetInput(itkMeshFileWriterMD2DTD22DD self, itkMeshD2DTD22DD input)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetInput(self, input)


    def GetInput(self, *args) -> "itkMeshD2DTD22DD const *":
        """
        GetInput(itkMeshFileWriterMD2DTD22DD self) -> itkMeshD2DTD22DD
        GetInput(itkMeshFileWriterMD2DTD22DD self, unsigned int idx) -> itkMeshD2DTD22DD
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetInput(self, *args)


    def SetFileName(self, *args) -> "void":
        """
        SetFileName(itkMeshFileWriterMD2DTD22DD self, char const * _arg)
        SetFileName(itkMeshFileWriterMD2DTD22DD self, std::string const & _arg)
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetFileName(self, *args)


    def GetFileName(self) -> "char const *":
        """GetFileName(itkMeshFileWriterMD2DTD22DD self) -> char const *"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetFileName(self)


    def SetMeshIO(self, io: 'itkMeshIOBase') -> "void":
        """SetMeshIO(itkMeshFileWriterMD2DTD22DD self, itkMeshIOBase io)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetMeshIO(self, io)


    def GetModifiableMeshIO(self) -> "itkMeshIOBase *":
        """GetModifiableMeshIO(itkMeshFileWriterMD2DTD22DD self) -> itkMeshIOBase"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetModifiableMeshIO(self)


    def GetMeshIO(self, *args) -> "itkMeshIOBase *":
        """
        GetMeshIO(itkMeshFileWriterMD2DTD22DD self) -> itkMeshIOBase
        GetMeshIO(itkMeshFileWriterMD2DTD22DD self) -> itkMeshIOBase
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetMeshIO(self, *args)


    def SetFileTypeAsASCII(self) -> "void":
        """SetFileTypeAsASCII(itkMeshFileWriterMD2DTD22DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetFileTypeAsASCII(self)


    def SetFileTypeAsBINARY(self) -> "void":
        """SetFileTypeAsBINARY(itkMeshFileWriterMD2DTD22DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetFileTypeAsBINARY(self)


    def Write(self) -> "void":
        """Write(itkMeshFileWriterMD2DTD22DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_Write(self)


    def SetUseCompression(self, _arg: 'bool const') -> "void":
        """SetUseCompression(itkMeshFileWriterMD2DTD22DD self, bool const _arg)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetUseCompression(self, _arg)


    def GetUseCompression(self) -> "bool const &":
        """GetUseCompression(itkMeshFileWriterMD2DTD22DD self) -> bool const &"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetUseCompression(self)


    def UseCompressionOn(self) -> "void":
        """UseCompressionOn(itkMeshFileWriterMD2DTD22DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_UseCompressionOn(self)


    def UseCompressionOff(self) -> "void":
        """UseCompressionOff(itkMeshFileWriterMD2DTD22DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_UseCompressionOff(self)

    __swig_destroy__ = _itkMeshFileWriterPython.delete_itkMeshFileWriterMD2DTD22DD

    def cast(obj: 'itkLightObject') -> "itkMeshFileWriterMD2DTD22DD *":
        """cast(itkLightObject obj) -> itkMeshFileWriterMD2DTD22DD"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMeshFileWriterMD2DTD22DD *":
        """GetPointer(itkMeshFileWriterMD2DTD22DD self) -> itkMeshFileWriterMD2DTD22DD"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMeshFileWriterMD2DTD22DD

        Create a new object of the class itkMeshFileWriterMD2DTD22DD and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMeshFileWriterMD2DTD22DD.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMeshFileWriterMD2DTD22DD.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMeshFileWriterMD2DTD22DD.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMeshFileWriterMD2DTD22DD.Clone = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_Clone, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.SetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetInput, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.GetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetInput, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.SetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetFileName, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.GetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetFileName, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.SetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetMeshIO, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.GetModifiableMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetModifiableMeshIO, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.GetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetMeshIO, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.SetFileTypeAsASCII = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetFileTypeAsASCII, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.SetFileTypeAsBINARY = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetFileTypeAsBINARY, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.Write = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_Write, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.SetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_SetUseCompression, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.GetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetUseCompression, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.UseCompressionOn = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_UseCompressionOn, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.UseCompressionOff = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_UseCompressionOff, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD.GetPointer = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_GetPointer, None, itkMeshFileWriterMD2DTD22DD)
itkMeshFileWriterMD2DTD22DD_swigregister = _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_swigregister
itkMeshFileWriterMD2DTD22DD_swigregister(itkMeshFileWriterMD2DTD22DD)

def itkMeshFileWriterMD2DTD22DD___New_orig__() -> "itkMeshFileWriterMD2DTD22DD_Pointer":
    """itkMeshFileWriterMD2DTD22DD___New_orig__() -> itkMeshFileWriterMD2DTD22DD_Pointer"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD___New_orig__()

def itkMeshFileWriterMD2DTD22DD_cast(obj: 'itkLightObject') -> "itkMeshFileWriterMD2DTD22DD *":
    """itkMeshFileWriterMD2DTD22DD_cast(itkLightObject obj) -> itkMeshFileWriterMD2DTD22DD"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMD2DTD22DD_cast(obj)

class itkMeshFileWriterMD2STD22DD(ITKCommonBasePython.itkProcessObject):
    """Proxy of C++ itkMeshFileWriterMD2STD22DD class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMeshFileWriterMD2STD22DD_Pointer":
        """__New_orig__() -> itkMeshFileWriterMD2STD22DD_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMeshFileWriterMD2STD22DD_Pointer":
        """Clone(itkMeshFileWriterMD2STD22DD self) -> itkMeshFileWriterMD2STD22DD_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_Clone(self)


    def SetInput(self, input: 'itkMeshD2STD22DD') -> "void":
        """SetInput(itkMeshFileWriterMD2STD22DD self, itkMeshD2STD22DD input)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetInput(self, input)


    def GetInput(self, *args) -> "itkMeshD2STD22DD const *":
        """
        GetInput(itkMeshFileWriterMD2STD22DD self) -> itkMeshD2STD22DD
        GetInput(itkMeshFileWriterMD2STD22DD self, unsigned int idx) -> itkMeshD2STD22DD
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetInput(self, *args)


    def SetFileName(self, *args) -> "void":
        """
        SetFileName(itkMeshFileWriterMD2STD22DD self, char const * _arg)
        SetFileName(itkMeshFileWriterMD2STD22DD self, std::string const & _arg)
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetFileName(self, *args)


    def GetFileName(self) -> "char const *":
        """GetFileName(itkMeshFileWriterMD2STD22DD self) -> char const *"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetFileName(self)


    def SetMeshIO(self, io: 'itkMeshIOBase') -> "void":
        """SetMeshIO(itkMeshFileWriterMD2STD22DD self, itkMeshIOBase io)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetMeshIO(self, io)


    def GetModifiableMeshIO(self) -> "itkMeshIOBase *":
        """GetModifiableMeshIO(itkMeshFileWriterMD2STD22DD self) -> itkMeshIOBase"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetModifiableMeshIO(self)


    def GetMeshIO(self, *args) -> "itkMeshIOBase *":
        """
        GetMeshIO(itkMeshFileWriterMD2STD22DD self) -> itkMeshIOBase
        GetMeshIO(itkMeshFileWriterMD2STD22DD self) -> itkMeshIOBase
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetMeshIO(self, *args)


    def SetFileTypeAsASCII(self) -> "void":
        """SetFileTypeAsASCII(itkMeshFileWriterMD2STD22DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetFileTypeAsASCII(self)


    def SetFileTypeAsBINARY(self) -> "void":
        """SetFileTypeAsBINARY(itkMeshFileWriterMD2STD22DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetFileTypeAsBINARY(self)


    def Write(self) -> "void":
        """Write(itkMeshFileWriterMD2STD22DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_Write(self)


    def SetUseCompression(self, _arg: 'bool const') -> "void":
        """SetUseCompression(itkMeshFileWriterMD2STD22DD self, bool const _arg)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetUseCompression(self, _arg)


    def GetUseCompression(self) -> "bool const &":
        """GetUseCompression(itkMeshFileWriterMD2STD22DD self) -> bool const &"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetUseCompression(self)


    def UseCompressionOn(self) -> "void":
        """UseCompressionOn(itkMeshFileWriterMD2STD22DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_UseCompressionOn(self)


    def UseCompressionOff(self) -> "void":
        """UseCompressionOff(itkMeshFileWriterMD2STD22DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_UseCompressionOff(self)

    __swig_destroy__ = _itkMeshFileWriterPython.delete_itkMeshFileWriterMD2STD22DD

    def cast(obj: 'itkLightObject') -> "itkMeshFileWriterMD2STD22DD *":
        """cast(itkLightObject obj) -> itkMeshFileWriterMD2STD22DD"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMeshFileWriterMD2STD22DD *":
        """GetPointer(itkMeshFileWriterMD2STD22DD self) -> itkMeshFileWriterMD2STD22DD"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMeshFileWriterMD2STD22DD

        Create a new object of the class itkMeshFileWriterMD2STD22DD and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMeshFileWriterMD2STD22DD.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMeshFileWriterMD2STD22DD.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMeshFileWriterMD2STD22DD.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMeshFileWriterMD2STD22DD.Clone = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_Clone, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.SetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetInput, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.GetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetInput, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.SetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetFileName, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.GetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetFileName, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.SetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetMeshIO, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.GetModifiableMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetModifiableMeshIO, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.GetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetMeshIO, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.SetFileTypeAsASCII = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetFileTypeAsASCII, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.SetFileTypeAsBINARY = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetFileTypeAsBINARY, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.Write = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_Write, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.SetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_SetUseCompression, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.GetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetUseCompression, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.UseCompressionOn = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_UseCompressionOn, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.UseCompressionOff = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_UseCompressionOff, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD.GetPointer = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_GetPointer, None, itkMeshFileWriterMD2STD22DD)
itkMeshFileWriterMD2STD22DD_swigregister = _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_swigregister
itkMeshFileWriterMD2STD22DD_swigregister(itkMeshFileWriterMD2STD22DD)

def itkMeshFileWriterMD2STD22DD___New_orig__() -> "itkMeshFileWriterMD2STD22DD_Pointer":
    """itkMeshFileWriterMD2STD22DD___New_orig__() -> itkMeshFileWriterMD2STD22DD_Pointer"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD___New_orig__()

def itkMeshFileWriterMD2STD22DD_cast(obj: 'itkLightObject') -> "itkMeshFileWriterMD2STD22DD *":
    """itkMeshFileWriterMD2STD22DD_cast(itkLightObject obj) -> itkMeshFileWriterMD2STD22DD"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMD2STD22DD_cast(obj)

class itkMeshFileWriterMD3DTD33DD(ITKCommonBasePython.itkProcessObject):
    """Proxy of C++ itkMeshFileWriterMD3DTD33DD class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMeshFileWriterMD3DTD33DD_Pointer":
        """__New_orig__() -> itkMeshFileWriterMD3DTD33DD_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMeshFileWriterMD3DTD33DD_Pointer":
        """Clone(itkMeshFileWriterMD3DTD33DD self) -> itkMeshFileWriterMD3DTD33DD_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_Clone(self)


    def SetInput(self, input: 'itkMeshD3DTD33DD') -> "void":
        """SetInput(itkMeshFileWriterMD3DTD33DD self, itkMeshD3DTD33DD input)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetInput(self, input)


    def GetInput(self, *args) -> "itkMeshD3DTD33DD const *":
        """
        GetInput(itkMeshFileWriterMD3DTD33DD self) -> itkMeshD3DTD33DD
        GetInput(itkMeshFileWriterMD3DTD33DD self, unsigned int idx) -> itkMeshD3DTD33DD
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetInput(self, *args)


    def SetFileName(self, *args) -> "void":
        """
        SetFileName(itkMeshFileWriterMD3DTD33DD self, char const * _arg)
        SetFileName(itkMeshFileWriterMD3DTD33DD self, std::string const & _arg)
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetFileName(self, *args)


    def GetFileName(self) -> "char const *":
        """GetFileName(itkMeshFileWriterMD3DTD33DD self) -> char const *"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetFileName(self)


    def SetMeshIO(self, io: 'itkMeshIOBase') -> "void":
        """SetMeshIO(itkMeshFileWriterMD3DTD33DD self, itkMeshIOBase io)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetMeshIO(self, io)


    def GetModifiableMeshIO(self) -> "itkMeshIOBase *":
        """GetModifiableMeshIO(itkMeshFileWriterMD3DTD33DD self) -> itkMeshIOBase"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetModifiableMeshIO(self)


    def GetMeshIO(self, *args) -> "itkMeshIOBase *":
        """
        GetMeshIO(itkMeshFileWriterMD3DTD33DD self) -> itkMeshIOBase
        GetMeshIO(itkMeshFileWriterMD3DTD33DD self) -> itkMeshIOBase
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetMeshIO(self, *args)


    def SetFileTypeAsASCII(self) -> "void":
        """SetFileTypeAsASCII(itkMeshFileWriterMD3DTD33DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetFileTypeAsASCII(self)


    def SetFileTypeAsBINARY(self) -> "void":
        """SetFileTypeAsBINARY(itkMeshFileWriterMD3DTD33DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetFileTypeAsBINARY(self)


    def Write(self) -> "void":
        """Write(itkMeshFileWriterMD3DTD33DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_Write(self)


    def SetUseCompression(self, _arg: 'bool const') -> "void":
        """SetUseCompression(itkMeshFileWriterMD3DTD33DD self, bool const _arg)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetUseCompression(self, _arg)


    def GetUseCompression(self) -> "bool const &":
        """GetUseCompression(itkMeshFileWriterMD3DTD33DD self) -> bool const &"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetUseCompression(self)


    def UseCompressionOn(self) -> "void":
        """UseCompressionOn(itkMeshFileWriterMD3DTD33DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_UseCompressionOn(self)


    def UseCompressionOff(self) -> "void":
        """UseCompressionOff(itkMeshFileWriterMD3DTD33DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_UseCompressionOff(self)

    __swig_destroy__ = _itkMeshFileWriterPython.delete_itkMeshFileWriterMD3DTD33DD

    def cast(obj: 'itkLightObject') -> "itkMeshFileWriterMD3DTD33DD *":
        """cast(itkLightObject obj) -> itkMeshFileWriterMD3DTD33DD"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMeshFileWriterMD3DTD33DD *":
        """GetPointer(itkMeshFileWriterMD3DTD33DD self) -> itkMeshFileWriterMD3DTD33DD"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMeshFileWriterMD3DTD33DD

        Create a new object of the class itkMeshFileWriterMD3DTD33DD and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMeshFileWriterMD3DTD33DD.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMeshFileWriterMD3DTD33DD.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMeshFileWriterMD3DTD33DD.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMeshFileWriterMD3DTD33DD.Clone = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_Clone, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.SetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetInput, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.GetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetInput, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.SetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetFileName, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.GetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetFileName, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.SetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetMeshIO, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.GetModifiableMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetModifiableMeshIO, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.GetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetMeshIO, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.SetFileTypeAsASCII = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetFileTypeAsASCII, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.SetFileTypeAsBINARY = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetFileTypeAsBINARY, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.Write = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_Write, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.SetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_SetUseCompression, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.GetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetUseCompression, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.UseCompressionOn = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_UseCompressionOn, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.UseCompressionOff = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_UseCompressionOff, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD.GetPointer = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_GetPointer, None, itkMeshFileWriterMD3DTD33DD)
itkMeshFileWriterMD3DTD33DD_swigregister = _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_swigregister
itkMeshFileWriterMD3DTD33DD_swigregister(itkMeshFileWriterMD3DTD33DD)

def itkMeshFileWriterMD3DTD33DD___New_orig__() -> "itkMeshFileWriterMD3DTD33DD_Pointer":
    """itkMeshFileWriterMD3DTD33DD___New_orig__() -> itkMeshFileWriterMD3DTD33DD_Pointer"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD___New_orig__()

def itkMeshFileWriterMD3DTD33DD_cast(obj: 'itkLightObject') -> "itkMeshFileWriterMD3DTD33DD *":
    """itkMeshFileWriterMD3DTD33DD_cast(itkLightObject obj) -> itkMeshFileWriterMD3DTD33DD"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMD3DTD33DD_cast(obj)

class itkMeshFileWriterMD3STD33DD(ITKCommonBasePython.itkProcessObject):
    """Proxy of C++ itkMeshFileWriterMD3STD33DD class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMeshFileWriterMD3STD33DD_Pointer":
        """__New_orig__() -> itkMeshFileWriterMD3STD33DD_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMeshFileWriterMD3STD33DD_Pointer":
        """Clone(itkMeshFileWriterMD3STD33DD self) -> itkMeshFileWriterMD3STD33DD_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_Clone(self)


    def SetInput(self, input: 'itkMeshD3STD33DD') -> "void":
        """SetInput(itkMeshFileWriterMD3STD33DD self, itkMeshD3STD33DD input)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetInput(self, input)


    def GetInput(self, *args) -> "itkMeshD3STD33DD const *":
        """
        GetInput(itkMeshFileWriterMD3STD33DD self) -> itkMeshD3STD33DD
        GetInput(itkMeshFileWriterMD3STD33DD self, unsigned int idx) -> itkMeshD3STD33DD
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetInput(self, *args)


    def SetFileName(self, *args) -> "void":
        """
        SetFileName(itkMeshFileWriterMD3STD33DD self, char const * _arg)
        SetFileName(itkMeshFileWriterMD3STD33DD self, std::string const & _arg)
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetFileName(self, *args)


    def GetFileName(self) -> "char const *":
        """GetFileName(itkMeshFileWriterMD3STD33DD self) -> char const *"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetFileName(self)


    def SetMeshIO(self, io: 'itkMeshIOBase') -> "void":
        """SetMeshIO(itkMeshFileWriterMD3STD33DD self, itkMeshIOBase io)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetMeshIO(self, io)


    def GetModifiableMeshIO(self) -> "itkMeshIOBase *":
        """GetModifiableMeshIO(itkMeshFileWriterMD3STD33DD self) -> itkMeshIOBase"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetModifiableMeshIO(self)


    def GetMeshIO(self, *args) -> "itkMeshIOBase *":
        """
        GetMeshIO(itkMeshFileWriterMD3STD33DD self) -> itkMeshIOBase
        GetMeshIO(itkMeshFileWriterMD3STD33DD self) -> itkMeshIOBase
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetMeshIO(self, *args)


    def SetFileTypeAsASCII(self) -> "void":
        """SetFileTypeAsASCII(itkMeshFileWriterMD3STD33DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetFileTypeAsASCII(self)


    def SetFileTypeAsBINARY(self) -> "void":
        """SetFileTypeAsBINARY(itkMeshFileWriterMD3STD33DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetFileTypeAsBINARY(self)


    def Write(self) -> "void":
        """Write(itkMeshFileWriterMD3STD33DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_Write(self)


    def SetUseCompression(self, _arg: 'bool const') -> "void":
        """SetUseCompression(itkMeshFileWriterMD3STD33DD self, bool const _arg)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetUseCompression(self, _arg)


    def GetUseCompression(self) -> "bool const &":
        """GetUseCompression(itkMeshFileWriterMD3STD33DD self) -> bool const &"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetUseCompression(self)


    def UseCompressionOn(self) -> "void":
        """UseCompressionOn(itkMeshFileWriterMD3STD33DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_UseCompressionOn(self)


    def UseCompressionOff(self) -> "void":
        """UseCompressionOff(itkMeshFileWriterMD3STD33DD self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_UseCompressionOff(self)

    __swig_destroy__ = _itkMeshFileWriterPython.delete_itkMeshFileWriterMD3STD33DD

    def cast(obj: 'itkLightObject') -> "itkMeshFileWriterMD3STD33DD *":
        """cast(itkLightObject obj) -> itkMeshFileWriterMD3STD33DD"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMeshFileWriterMD3STD33DD *":
        """GetPointer(itkMeshFileWriterMD3STD33DD self) -> itkMeshFileWriterMD3STD33DD"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMeshFileWriterMD3STD33DD

        Create a new object of the class itkMeshFileWriterMD3STD33DD and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMeshFileWriterMD3STD33DD.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMeshFileWriterMD3STD33DD.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMeshFileWriterMD3STD33DD.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMeshFileWriterMD3STD33DD.Clone = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_Clone, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.SetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetInput, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.GetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetInput, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.SetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetFileName, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.GetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetFileName, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.SetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetMeshIO, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.GetModifiableMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetModifiableMeshIO, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.GetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetMeshIO, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.SetFileTypeAsASCII = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetFileTypeAsASCII, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.SetFileTypeAsBINARY = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetFileTypeAsBINARY, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.Write = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_Write, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.SetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_SetUseCompression, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.GetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetUseCompression, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.UseCompressionOn = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_UseCompressionOn, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.UseCompressionOff = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_UseCompressionOff, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD.GetPointer = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_GetPointer, None, itkMeshFileWriterMD3STD33DD)
itkMeshFileWriterMD3STD33DD_swigregister = _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_swigregister
itkMeshFileWriterMD3STD33DD_swigregister(itkMeshFileWriterMD3STD33DD)

def itkMeshFileWriterMD3STD33DD___New_orig__() -> "itkMeshFileWriterMD3STD33DD_Pointer":
    """itkMeshFileWriterMD3STD33DD___New_orig__() -> itkMeshFileWriterMD3STD33DD_Pointer"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD___New_orig__()

def itkMeshFileWriterMD3STD33DD_cast(obj: 'itkLightObject') -> "itkMeshFileWriterMD3STD33DD *":
    """itkMeshFileWriterMD3STD33DD_cast(itkLightObject obj) -> itkMeshFileWriterMD3STD33DD"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMD3STD33DD_cast(obj)

class itkMeshFileWriterMF2DTF22FF(ITKCommonBasePython.itkProcessObject):
    """Proxy of C++ itkMeshFileWriterMF2DTF22FF class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMeshFileWriterMF2DTF22FF_Pointer":
        """__New_orig__() -> itkMeshFileWriterMF2DTF22FF_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMeshFileWriterMF2DTF22FF_Pointer":
        """Clone(itkMeshFileWriterMF2DTF22FF self) -> itkMeshFileWriterMF2DTF22FF_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_Clone(self)


    def SetInput(self, input: 'itkMeshF2DTF22FF') -> "void":
        """SetInput(itkMeshFileWriterMF2DTF22FF self, itkMeshF2DTF22FF input)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetInput(self, input)


    def GetInput(self, *args) -> "itkMeshF2DTF22FF const *":
        """
        GetInput(itkMeshFileWriterMF2DTF22FF self) -> itkMeshF2DTF22FF
        GetInput(itkMeshFileWriterMF2DTF22FF self, unsigned int idx) -> itkMeshF2DTF22FF
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetInput(self, *args)


    def SetFileName(self, *args) -> "void":
        """
        SetFileName(itkMeshFileWriterMF2DTF22FF self, char const * _arg)
        SetFileName(itkMeshFileWriterMF2DTF22FF self, std::string const & _arg)
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetFileName(self, *args)


    def GetFileName(self) -> "char const *":
        """GetFileName(itkMeshFileWriterMF2DTF22FF self) -> char const *"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetFileName(self)


    def SetMeshIO(self, io: 'itkMeshIOBase') -> "void":
        """SetMeshIO(itkMeshFileWriterMF2DTF22FF self, itkMeshIOBase io)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetMeshIO(self, io)


    def GetModifiableMeshIO(self) -> "itkMeshIOBase *":
        """GetModifiableMeshIO(itkMeshFileWriterMF2DTF22FF self) -> itkMeshIOBase"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetModifiableMeshIO(self)


    def GetMeshIO(self, *args) -> "itkMeshIOBase *":
        """
        GetMeshIO(itkMeshFileWriterMF2DTF22FF self) -> itkMeshIOBase
        GetMeshIO(itkMeshFileWriterMF2DTF22FF self) -> itkMeshIOBase
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetMeshIO(self, *args)


    def SetFileTypeAsASCII(self) -> "void":
        """SetFileTypeAsASCII(itkMeshFileWriterMF2DTF22FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetFileTypeAsASCII(self)


    def SetFileTypeAsBINARY(self) -> "void":
        """SetFileTypeAsBINARY(itkMeshFileWriterMF2DTF22FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetFileTypeAsBINARY(self)


    def Write(self) -> "void":
        """Write(itkMeshFileWriterMF2DTF22FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_Write(self)


    def SetUseCompression(self, _arg: 'bool const') -> "void":
        """SetUseCompression(itkMeshFileWriterMF2DTF22FF self, bool const _arg)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetUseCompression(self, _arg)


    def GetUseCompression(self) -> "bool const &":
        """GetUseCompression(itkMeshFileWriterMF2DTF22FF self) -> bool const &"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetUseCompression(self)


    def UseCompressionOn(self) -> "void":
        """UseCompressionOn(itkMeshFileWriterMF2DTF22FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_UseCompressionOn(self)


    def UseCompressionOff(self) -> "void":
        """UseCompressionOff(itkMeshFileWriterMF2DTF22FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_UseCompressionOff(self)

    __swig_destroy__ = _itkMeshFileWriterPython.delete_itkMeshFileWriterMF2DTF22FF

    def cast(obj: 'itkLightObject') -> "itkMeshFileWriterMF2DTF22FF *":
        """cast(itkLightObject obj) -> itkMeshFileWriterMF2DTF22FF"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMeshFileWriterMF2DTF22FF *":
        """GetPointer(itkMeshFileWriterMF2DTF22FF self) -> itkMeshFileWriterMF2DTF22FF"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMeshFileWriterMF2DTF22FF

        Create a new object of the class itkMeshFileWriterMF2DTF22FF and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMeshFileWriterMF2DTF22FF.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMeshFileWriterMF2DTF22FF.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMeshFileWriterMF2DTF22FF.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMeshFileWriterMF2DTF22FF.Clone = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_Clone, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.SetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetInput, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.GetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetInput, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.SetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetFileName, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.GetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetFileName, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.SetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetMeshIO, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.GetModifiableMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetModifiableMeshIO, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.GetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetMeshIO, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.SetFileTypeAsASCII = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetFileTypeAsASCII, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.SetFileTypeAsBINARY = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetFileTypeAsBINARY, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.Write = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_Write, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.SetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_SetUseCompression, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.GetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetUseCompression, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.UseCompressionOn = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_UseCompressionOn, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.UseCompressionOff = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_UseCompressionOff, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF.GetPointer = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_GetPointer, None, itkMeshFileWriterMF2DTF22FF)
itkMeshFileWriterMF2DTF22FF_swigregister = _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_swigregister
itkMeshFileWriterMF2DTF22FF_swigregister(itkMeshFileWriterMF2DTF22FF)

def itkMeshFileWriterMF2DTF22FF___New_orig__() -> "itkMeshFileWriterMF2DTF22FF_Pointer":
    """itkMeshFileWriterMF2DTF22FF___New_orig__() -> itkMeshFileWriterMF2DTF22FF_Pointer"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF___New_orig__()

def itkMeshFileWriterMF2DTF22FF_cast(obj: 'itkLightObject') -> "itkMeshFileWriterMF2DTF22FF *":
    """itkMeshFileWriterMF2DTF22FF_cast(itkLightObject obj) -> itkMeshFileWriterMF2DTF22FF"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMF2DTF22FF_cast(obj)

class itkMeshFileWriterMF2STF22FF(ITKCommonBasePython.itkProcessObject):
    """Proxy of C++ itkMeshFileWriterMF2STF22FF class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMeshFileWriterMF2STF22FF_Pointer":
        """__New_orig__() -> itkMeshFileWriterMF2STF22FF_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMeshFileWriterMF2STF22FF_Pointer":
        """Clone(itkMeshFileWriterMF2STF22FF self) -> itkMeshFileWriterMF2STF22FF_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_Clone(self)


    def SetInput(self, input: 'itkMeshF2STF22FF') -> "void":
        """SetInput(itkMeshFileWriterMF2STF22FF self, itkMeshF2STF22FF input)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetInput(self, input)


    def GetInput(self, *args) -> "itkMeshF2STF22FF const *":
        """
        GetInput(itkMeshFileWriterMF2STF22FF self) -> itkMeshF2STF22FF
        GetInput(itkMeshFileWriterMF2STF22FF self, unsigned int idx) -> itkMeshF2STF22FF
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetInput(self, *args)


    def SetFileName(self, *args) -> "void":
        """
        SetFileName(itkMeshFileWriterMF2STF22FF self, char const * _arg)
        SetFileName(itkMeshFileWriterMF2STF22FF self, std::string const & _arg)
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetFileName(self, *args)


    def GetFileName(self) -> "char const *":
        """GetFileName(itkMeshFileWriterMF2STF22FF self) -> char const *"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetFileName(self)


    def SetMeshIO(self, io: 'itkMeshIOBase') -> "void":
        """SetMeshIO(itkMeshFileWriterMF2STF22FF self, itkMeshIOBase io)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetMeshIO(self, io)


    def GetModifiableMeshIO(self) -> "itkMeshIOBase *":
        """GetModifiableMeshIO(itkMeshFileWriterMF2STF22FF self) -> itkMeshIOBase"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetModifiableMeshIO(self)


    def GetMeshIO(self, *args) -> "itkMeshIOBase *":
        """
        GetMeshIO(itkMeshFileWriterMF2STF22FF self) -> itkMeshIOBase
        GetMeshIO(itkMeshFileWriterMF2STF22FF self) -> itkMeshIOBase
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetMeshIO(self, *args)


    def SetFileTypeAsASCII(self) -> "void":
        """SetFileTypeAsASCII(itkMeshFileWriterMF2STF22FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetFileTypeAsASCII(self)


    def SetFileTypeAsBINARY(self) -> "void":
        """SetFileTypeAsBINARY(itkMeshFileWriterMF2STF22FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetFileTypeAsBINARY(self)


    def Write(self) -> "void":
        """Write(itkMeshFileWriterMF2STF22FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_Write(self)


    def SetUseCompression(self, _arg: 'bool const') -> "void":
        """SetUseCompression(itkMeshFileWriterMF2STF22FF self, bool const _arg)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetUseCompression(self, _arg)


    def GetUseCompression(self) -> "bool const &":
        """GetUseCompression(itkMeshFileWriterMF2STF22FF self) -> bool const &"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetUseCompression(self)


    def UseCompressionOn(self) -> "void":
        """UseCompressionOn(itkMeshFileWriterMF2STF22FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_UseCompressionOn(self)


    def UseCompressionOff(self) -> "void":
        """UseCompressionOff(itkMeshFileWriterMF2STF22FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_UseCompressionOff(self)

    __swig_destroy__ = _itkMeshFileWriterPython.delete_itkMeshFileWriterMF2STF22FF

    def cast(obj: 'itkLightObject') -> "itkMeshFileWriterMF2STF22FF *":
        """cast(itkLightObject obj) -> itkMeshFileWriterMF2STF22FF"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMeshFileWriterMF2STF22FF *":
        """GetPointer(itkMeshFileWriterMF2STF22FF self) -> itkMeshFileWriterMF2STF22FF"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMeshFileWriterMF2STF22FF

        Create a new object of the class itkMeshFileWriterMF2STF22FF and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMeshFileWriterMF2STF22FF.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMeshFileWriterMF2STF22FF.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMeshFileWriterMF2STF22FF.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMeshFileWriterMF2STF22FF.Clone = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_Clone, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.SetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetInput, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.GetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetInput, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.SetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetFileName, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.GetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetFileName, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.SetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetMeshIO, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.GetModifiableMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetModifiableMeshIO, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.GetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetMeshIO, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.SetFileTypeAsASCII = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetFileTypeAsASCII, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.SetFileTypeAsBINARY = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetFileTypeAsBINARY, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.Write = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_Write, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.SetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_SetUseCompression, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.GetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetUseCompression, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.UseCompressionOn = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_UseCompressionOn, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.UseCompressionOff = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_UseCompressionOff, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF.GetPointer = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_GetPointer, None, itkMeshFileWriterMF2STF22FF)
itkMeshFileWriterMF2STF22FF_swigregister = _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_swigregister
itkMeshFileWriterMF2STF22FF_swigregister(itkMeshFileWriterMF2STF22FF)

def itkMeshFileWriterMF2STF22FF___New_orig__() -> "itkMeshFileWriterMF2STF22FF_Pointer":
    """itkMeshFileWriterMF2STF22FF___New_orig__() -> itkMeshFileWriterMF2STF22FF_Pointer"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF___New_orig__()

def itkMeshFileWriterMF2STF22FF_cast(obj: 'itkLightObject') -> "itkMeshFileWriterMF2STF22FF *":
    """itkMeshFileWriterMF2STF22FF_cast(itkLightObject obj) -> itkMeshFileWriterMF2STF22FF"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMF2STF22FF_cast(obj)

class itkMeshFileWriterMF3DTF33FF(ITKCommonBasePython.itkProcessObject):
    """Proxy of C++ itkMeshFileWriterMF3DTF33FF class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMeshFileWriterMF3DTF33FF_Pointer":
        """__New_orig__() -> itkMeshFileWriterMF3DTF33FF_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMeshFileWriterMF3DTF33FF_Pointer":
        """Clone(itkMeshFileWriterMF3DTF33FF self) -> itkMeshFileWriterMF3DTF33FF_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_Clone(self)


    def SetInput(self, input: 'itkMeshF3DTF33FF') -> "void":
        """SetInput(itkMeshFileWriterMF3DTF33FF self, itkMeshF3DTF33FF input)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetInput(self, input)


    def GetInput(self, *args) -> "itkMeshF3DTF33FF const *":
        """
        GetInput(itkMeshFileWriterMF3DTF33FF self) -> itkMeshF3DTF33FF
        GetInput(itkMeshFileWriterMF3DTF33FF self, unsigned int idx) -> itkMeshF3DTF33FF
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetInput(self, *args)


    def SetFileName(self, *args) -> "void":
        """
        SetFileName(itkMeshFileWriterMF3DTF33FF self, char const * _arg)
        SetFileName(itkMeshFileWriterMF3DTF33FF self, std::string const & _arg)
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetFileName(self, *args)


    def GetFileName(self) -> "char const *":
        """GetFileName(itkMeshFileWriterMF3DTF33FF self) -> char const *"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetFileName(self)


    def SetMeshIO(self, io: 'itkMeshIOBase') -> "void":
        """SetMeshIO(itkMeshFileWriterMF3DTF33FF self, itkMeshIOBase io)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetMeshIO(self, io)


    def GetModifiableMeshIO(self) -> "itkMeshIOBase *":
        """GetModifiableMeshIO(itkMeshFileWriterMF3DTF33FF self) -> itkMeshIOBase"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetModifiableMeshIO(self)


    def GetMeshIO(self, *args) -> "itkMeshIOBase *":
        """
        GetMeshIO(itkMeshFileWriterMF3DTF33FF self) -> itkMeshIOBase
        GetMeshIO(itkMeshFileWriterMF3DTF33FF self) -> itkMeshIOBase
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetMeshIO(self, *args)


    def SetFileTypeAsASCII(self) -> "void":
        """SetFileTypeAsASCII(itkMeshFileWriterMF3DTF33FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetFileTypeAsASCII(self)


    def SetFileTypeAsBINARY(self) -> "void":
        """SetFileTypeAsBINARY(itkMeshFileWriterMF3DTF33FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetFileTypeAsBINARY(self)


    def Write(self) -> "void":
        """Write(itkMeshFileWriterMF3DTF33FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_Write(self)


    def SetUseCompression(self, _arg: 'bool const') -> "void":
        """SetUseCompression(itkMeshFileWriterMF3DTF33FF self, bool const _arg)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetUseCompression(self, _arg)


    def GetUseCompression(self) -> "bool const &":
        """GetUseCompression(itkMeshFileWriterMF3DTF33FF self) -> bool const &"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetUseCompression(self)


    def UseCompressionOn(self) -> "void":
        """UseCompressionOn(itkMeshFileWriterMF3DTF33FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_UseCompressionOn(self)


    def UseCompressionOff(self) -> "void":
        """UseCompressionOff(itkMeshFileWriterMF3DTF33FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_UseCompressionOff(self)

    __swig_destroy__ = _itkMeshFileWriterPython.delete_itkMeshFileWriterMF3DTF33FF

    def cast(obj: 'itkLightObject') -> "itkMeshFileWriterMF3DTF33FF *":
        """cast(itkLightObject obj) -> itkMeshFileWriterMF3DTF33FF"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMeshFileWriterMF3DTF33FF *":
        """GetPointer(itkMeshFileWriterMF3DTF33FF self) -> itkMeshFileWriterMF3DTF33FF"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMeshFileWriterMF3DTF33FF

        Create a new object of the class itkMeshFileWriterMF3DTF33FF and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMeshFileWriterMF3DTF33FF.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMeshFileWriterMF3DTF33FF.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMeshFileWriterMF3DTF33FF.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMeshFileWriterMF3DTF33FF.Clone = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_Clone, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.SetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetInput, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.GetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetInput, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.SetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetFileName, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.GetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetFileName, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.SetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetMeshIO, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.GetModifiableMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetModifiableMeshIO, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.GetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetMeshIO, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.SetFileTypeAsASCII = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetFileTypeAsASCII, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.SetFileTypeAsBINARY = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetFileTypeAsBINARY, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.Write = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_Write, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.SetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_SetUseCompression, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.GetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetUseCompression, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.UseCompressionOn = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_UseCompressionOn, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.UseCompressionOff = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_UseCompressionOff, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF.GetPointer = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_GetPointer, None, itkMeshFileWriterMF3DTF33FF)
itkMeshFileWriterMF3DTF33FF_swigregister = _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_swigregister
itkMeshFileWriterMF3DTF33FF_swigregister(itkMeshFileWriterMF3DTF33FF)

def itkMeshFileWriterMF3DTF33FF___New_orig__() -> "itkMeshFileWriterMF3DTF33FF_Pointer":
    """itkMeshFileWriterMF3DTF33FF___New_orig__() -> itkMeshFileWriterMF3DTF33FF_Pointer"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF___New_orig__()

def itkMeshFileWriterMF3DTF33FF_cast(obj: 'itkLightObject') -> "itkMeshFileWriterMF3DTF33FF *":
    """itkMeshFileWriterMF3DTF33FF_cast(itkLightObject obj) -> itkMeshFileWriterMF3DTF33FF"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMF3DTF33FF_cast(obj)

class itkMeshFileWriterMF3STF33FF(ITKCommonBasePython.itkProcessObject):
    """Proxy of C++ itkMeshFileWriterMF3STF33FF class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMeshFileWriterMF3STF33FF_Pointer":
        """__New_orig__() -> itkMeshFileWriterMF3STF33FF_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMeshFileWriterMF3STF33FF_Pointer":
        """Clone(itkMeshFileWriterMF3STF33FF self) -> itkMeshFileWriterMF3STF33FF_Pointer"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_Clone(self)


    def SetInput(self, input: 'itkMeshF3STF33FF') -> "void":
        """SetInput(itkMeshFileWriterMF3STF33FF self, itkMeshF3STF33FF input)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetInput(self, input)


    def GetInput(self, *args) -> "itkMeshF3STF33FF const *":
        """
        GetInput(itkMeshFileWriterMF3STF33FF self) -> itkMeshF3STF33FF
        GetInput(itkMeshFileWriterMF3STF33FF self, unsigned int idx) -> itkMeshF3STF33FF
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetInput(self, *args)


    def SetFileName(self, *args) -> "void":
        """
        SetFileName(itkMeshFileWriterMF3STF33FF self, char const * _arg)
        SetFileName(itkMeshFileWriterMF3STF33FF self, std::string const & _arg)
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetFileName(self, *args)


    def GetFileName(self) -> "char const *":
        """GetFileName(itkMeshFileWriterMF3STF33FF self) -> char const *"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetFileName(self)


    def SetMeshIO(self, io: 'itkMeshIOBase') -> "void":
        """SetMeshIO(itkMeshFileWriterMF3STF33FF self, itkMeshIOBase io)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetMeshIO(self, io)


    def GetModifiableMeshIO(self) -> "itkMeshIOBase *":
        """GetModifiableMeshIO(itkMeshFileWriterMF3STF33FF self) -> itkMeshIOBase"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetModifiableMeshIO(self)


    def GetMeshIO(self, *args) -> "itkMeshIOBase *":
        """
        GetMeshIO(itkMeshFileWriterMF3STF33FF self) -> itkMeshIOBase
        GetMeshIO(itkMeshFileWriterMF3STF33FF self) -> itkMeshIOBase
        """
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetMeshIO(self, *args)


    def SetFileTypeAsASCII(self) -> "void":
        """SetFileTypeAsASCII(itkMeshFileWriterMF3STF33FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetFileTypeAsASCII(self)


    def SetFileTypeAsBINARY(self) -> "void":
        """SetFileTypeAsBINARY(itkMeshFileWriterMF3STF33FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetFileTypeAsBINARY(self)


    def Write(self) -> "void":
        """Write(itkMeshFileWriterMF3STF33FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_Write(self)


    def SetUseCompression(self, _arg: 'bool const') -> "void":
        """SetUseCompression(itkMeshFileWriterMF3STF33FF self, bool const _arg)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetUseCompression(self, _arg)


    def GetUseCompression(self) -> "bool const &":
        """GetUseCompression(itkMeshFileWriterMF3STF33FF self) -> bool const &"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetUseCompression(self)


    def UseCompressionOn(self) -> "void":
        """UseCompressionOn(itkMeshFileWriterMF3STF33FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_UseCompressionOn(self)


    def UseCompressionOff(self) -> "void":
        """UseCompressionOff(itkMeshFileWriterMF3STF33FF self)"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_UseCompressionOff(self)

    __swig_destroy__ = _itkMeshFileWriterPython.delete_itkMeshFileWriterMF3STF33FF

    def cast(obj: 'itkLightObject') -> "itkMeshFileWriterMF3STF33FF *":
        """cast(itkLightObject obj) -> itkMeshFileWriterMF3STF33FF"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMeshFileWriterMF3STF33FF *":
        """GetPointer(itkMeshFileWriterMF3STF33FF self) -> itkMeshFileWriterMF3STF33FF"""
        return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMeshFileWriterMF3STF33FF

        Create a new object of the class itkMeshFileWriterMF3STF33FF and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMeshFileWriterMF3STF33FF.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMeshFileWriterMF3STF33FF.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMeshFileWriterMF3STF33FF.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMeshFileWriterMF3STF33FF.Clone = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_Clone, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.SetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetInput, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.GetInput = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetInput, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.SetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetFileName, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.GetFileName = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetFileName, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.SetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetMeshIO, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.GetModifiableMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetModifiableMeshIO, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.GetMeshIO = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetMeshIO, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.SetFileTypeAsASCII = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetFileTypeAsASCII, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.SetFileTypeAsBINARY = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetFileTypeAsBINARY, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.Write = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_Write, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.SetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_SetUseCompression, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.GetUseCompression = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetUseCompression, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.UseCompressionOn = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_UseCompressionOn, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.UseCompressionOff = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_UseCompressionOff, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF.GetPointer = new_instancemethod(_itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_GetPointer, None, itkMeshFileWriterMF3STF33FF)
itkMeshFileWriterMF3STF33FF_swigregister = _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_swigregister
itkMeshFileWriterMF3STF33FF_swigregister(itkMeshFileWriterMF3STF33FF)

def itkMeshFileWriterMF3STF33FF___New_orig__() -> "itkMeshFileWriterMF3STF33FF_Pointer":
    """itkMeshFileWriterMF3STF33FF___New_orig__() -> itkMeshFileWriterMF3STF33FF_Pointer"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF___New_orig__()

def itkMeshFileWriterMF3STF33FF_cast(obj: 'itkLightObject') -> "itkMeshFileWriterMF3STF33FF *":
    """itkMeshFileWriterMF3STF33FF_cast(itkLightObject obj) -> itkMeshFileWriterMF3STF33FF"""
    return _itkMeshFileWriterPython.itkMeshFileWriterMF3STF33FF_cast(obj)



