# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-12 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoanalytics', '0002_auto_20190208_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawcid',
            old_name='dimensions',
            new_name='cid_dimensions',
        ),
        migrations.RenameField(
            model_name='rawcid',
            old_name='metrics',
            new_name='cid_metrics',
        ),
        migrations.RenameField(
            model_name='rawhit',
            old_name='custom_dimensions',
            new_name='hit_custom_dimensions',
        ),
        migrations.RenameField(
            model_name='rawhit',
            old_name='custom_metrics',
            new_name='hit_custom_metrics',
        ),
    ]
