
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-12T10:43:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "baea80ce5048bb54ea53a5101a9ad87c98f9da06",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
