# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/orsinium/dephell

from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(here, 'README.rst'), encoding='utf-8') as stream:
    readme = stream.read()

setup(
    long_description=readme,
    packages=['dephell_archive'],
    name='dephell-archive',
    version='0.1.0',
    description='pathlib for archives',
    python_requires='>=3.5',
    author='orsinium',
    install_requires=['attrs'],
)
