# DO NOT EDIT THIS FILE!
#
# Python module RTC generated by omniidl

import omniORB
omniORB.updateModule("rtctree.rtc.RTC")

# ** 1. Stub files contributing to this module
import rtctree.rtc.BasicDataType_idl
import rtctree.rtc.ComponentObserver_idl
import rtctree.rtc.ExtendedDataTypes_idl
import rtctree.rtc.ExtendedFsmService_idl
import rtctree.rtc.InterfaceDataTypes_idl
import rtctree.rtc.RTC_idl

# ** 2. Sub-modules

# ** 3. End
