[tool.poetry]
name = "bouchon"
version = "0.1.4"
description = ""
authors = ["Romain Dorgueil <romain@dorgueil.net>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.0"
gunicorn = "^19.9"


[tool.poetry.dev-dependencies]
pytest = "^4.3"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
