from enum import Enum


class ActionMode(Enum):
    CHANGE_SET_EXECUTE = "CHANGE_SET_EXECUTE"
    CHANGE_SET_REPLACE = "CHANGE_SET_REPLACE"
    CREATE_UPDATE = "CREATE_UPDATE"
    DELETE_ONLY = "DELETE_ONLY"
    REPLACE_ON_FAILURE = "REPLACE_ON_FAILURE"
