# Generated by Django 2.1.4 on 2019-03-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0003_remove_useraddress_address_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=7)),
                ('value', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country State Translations',
                'ordering': ['language', 'state'],
            },
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=7)),
                ('value', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleboxdjango.Country')),
            ],
            options={
                'verbose_name': 'Country Translations',
                'ordering': ['language', 'country'],
            },
        ),
        migrations.AlterModelOptions(
            name='countrystate',
            options={'ordering': ['name'], 'verbose_name_plural': 'Country States'},
        ),
        migrations.AddField(
            model_name='countrystatetranslation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleboxdjango.CountryState'),
        ),
    ]
