
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-11T11:58:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad2df1faebabd72810d12552306792071c109d64",
 "version": "0.24.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
