[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "parallelic"
version = "0.1.3"
license = "MPL-2.0"
description = "Hyper-parallel multi-node task execution engine"
authors = ["golyalpha <golyalpha@gmail.com>"]
readme = "readme.md"
repository = "https://gitlab.com/OnDev-Project/parallelic"
classifiers = [
	"Development Status :: 1 - Planning"
]

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"
udp-filetransfer = "^0.1.2"
sqlobject = "^3.7"
psycopg2-binary = "^2.7"
flask = {version = "^1.0",optional = true}
flask-assets = {version = "^0.12.0",optional = true}
flask-compress = {version = "^1.4",optional = true}
flask-wtf = {version = "^0.14.2",optional = true}
flask-login = {version = "^0.4.1",optional = true}
jsmin = {version = "^2.2",optional = true}
bcrypt = {version = "^3.1",optional = true}
cssutils = {version = "^1.0",optional = true}
gunicorn = {version = "^19.9",optional = true}


[tool.poetry.dev-dependencies]
pylint = "^2.2"
pytest = "^4.0"
pytest-cov = "^2.6"

[tool.poetry.scripts]
parallelic = "parallelic:main"
