[tool.poetry]
name = "shopify-requests"
version = "0.1.1"
description = "Wrapper around the Shopify API using requests."
authors = ["Paul Robertson <t.paulrobertson@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/perobertson/shopify-requests"
keywords = [
  "shopify",
  "requests"
]

[tool.poetry.dependencies]
python = "^2.7"
requests = "^2.21"

[tool.poetry.dev-dependencies]
flake8 = "^3.6"
pytest = "^4.0"
pytest-cov = "^2.6"
requests_mock = "^1.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
