
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-16T17:26:40-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "6cbd871329b30663902a5515fd95a5bb2579b5bb",
 "version": "v2019.3.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
