# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-03-07T14:49:30.199525'

__version__ = '2019.3'
__sha__ = '61a6c23f7a1404a6cdef3447a0b37fdb732612d6'
__revision__ = '61a6c23f7a1404a6cdef3447a0b37fdb732612d6'
