name: test_site
description: All the details of the site.All the details
    the site.All the details of the site.All the details of the
    site.All the details of the site.All the details of the
    site.All the details of the site.
street: Teststrasse 1
postcode:
city: 8048 Zurich, Switzerland
coordinates:
    x: 580000
    y: 255300
    z: 455.3

# pictures are optional:
pictures:
    -
      path: images/IMG_0312.JPG
      description: outside
      # timestamp is optional:
      timestamp: 2016/02/01 12:00:00
    -
      path: images/IMG_0732.JPG
      description: manholeD1
