
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-14T16:18:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e228ec4f581716d8e61e021919a46951f9ffedc",
 "version": "v3.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
