# Generated by Django 2.1.3 on 2018-12-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0003_auto_20181206_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='selectable',
            field=models.BooleanField(default=True, verbose_name='可选择'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='selectable',
            field=models.BooleanField(default=True, verbose_name='可选择'),
        ),
    ]
