# Generated by Django 2.1.3 on 2019-01-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0012_auto_20190107_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='data_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='帮助文本'),
        ),
        migrations.AlterField(
            model_name='field',
            name='max_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大长度'),
        ),
        migrations.AlterField(
            model_name='field',
            name='serialize',
            field=models.BooleanField(blank=True, null=True, verbose_name='可序列化'),
        ),
        migrations.AlterField(
            model_name='groupfield',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='帮助文本'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='帮助文本'),
        ),
    ]
