# Generated by Django 2.1.5 on 2019-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('font_icons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonticonmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
