# -*- coding: utf-8 -*-

# Generated by Django 1.11 on 2017-09-11 16:42


from django.db import migrations
import djangoplus.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoa_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='documento',
            field=djangoplus.db.models.fields.CharField(max_length=255, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo',
            field=djangoplus.db.models.fields.CharField(choices=[['F\xedsica', 'F\xedsica'], ['Jur\xeddica', 'Jur\xeddica']], max_length=255, null=True, verbose_name='Tipo'),
        ),
    ]
