dist: xenial
group: travis_latest
cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  include:
    - python: "2.6"
      dist: trusty
    - python: "2.7"
    - python: "3.3"
      dist: trusty
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"

install:
  - "pip install ."

script: make test
