[tool.poetry]
name = "simple_test_default_reporter"
version = "0.2.0"
description = "The default reporter for simple_test"
authors = ["Philip Olson <philip.olson@pm.me>"]
license = "WTFNMFPL-1.0"
readme = "README.md"
repository = "https://github.com/olsonpm/py_simple-test-default-reporter"
include = ["license.txt"]

[tool.poetry.dependencies]
python = "^3.7"
simple_chalk = "^0.1.0"
wrapt = "^1.10"
ordered_set = "^3.1"
tedent = "^0.1.1"

[tool.poetry.dev-dependencies]
pretty_simple_namespace = "^0.1.0"
toml = "^0.10.0"
is_git_repo_clean = "^0.3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
