
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-14T00:33:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ea7008ec714e8000aede3478f0a3abff3f7bf46",
 "version": "0.0.1.post.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
