[package]
name = "ed25519-dalek"
version = "1.0.0-pre.2"
authors = ["isis lovecruft <isis@patternsinthevoid.net>", "namuyan <thhjuuATyahoo.co.jp>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/namuyan/ed25519-dalek"
homepage = "https://dalek.rs"
documentation = "https://docs.rs/ed25519-dalek"
keywords = ["cryptography", "ed25519", "curve25519", "signature", "ECC"]
categories = ["cryptography", "no-std"]
description = "Fast and efficient ed25519 EdDSA key generations, signing, and verification in pure Rust."
exclude = [ ".gitignore", "TESTVECTORS", "res/*" ]

[lib]
name = "nem_ed25519_rust"
crate-type = ["lib", "cdylib"]

[badges]
travis-ci = { repository = "dalek-cryptography/ed25519-dalek", branch = "master"}

[dependencies.curve25519-dalek]
version = "1"
default-features = false

[dependencies.rand]
version = "0.6"
features = ["i128_support"]

[dependencies.serde]
version = "^1.0"
optional = true

[dependencies.sha3]
version = "^0.8"
default-features = false

[dependencies.failure]
version = "^0.1.1"
default-features = false

[dependencies.clear_on_drop]
version = "0.2"

[dependencies.aes-soft]
version = "^0.3.2"

[dependencies.block-modes]
version = "^0.3.2"

[dependencies.pyo3]
version = "0.6.0-alpha.4"
features = ["extension-module"]
optional = true

[dev-dependencies]
hex = "^0.3"
bincode = "^0.9"
criterion = "0.2"

[[bench]]
name = "ed25519_benchmarks"
harness = false

[features]
default = ["std", "u64_backend"]
std = ["curve25519-dalek/std", "rand/std", "sha3/std"]
alloc = ["curve25519-dalek/alloc"]
nightly = ["curve25519-dalek/nightly", "rand/nightly", "clear_on_drop/nightly"]
yolocrypto = ["curve25519-dalek/yolocrypto"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend"]
pylib = ["pyo3"]
