[tool.poetry]
name = "flask-dramatiq"
version = "0.1.0"
description = "Adds Dramatiq support to your Flask application"
authors = ["Étienne BERSAC"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
