language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install coveralls
script:
  - coverage run --source=ctshed setup.py test
after_success:
  - coveralls
