
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1e4361cd7c10b2941c8bb2444203d04e870cf45c",
 "version": "2107"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
