language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - nightly
env:
  - REDIS_PY=2.10.6
  - REDIS_PY=3.0.1
  - REDIS_PY=3.1.0
  - REDIS_PY=3.2.1
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
sudo: false
# Python 3.7 isn't available on trusty, so needs a separate build config
cache:
  - pip
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install redis==$REDIS_PY
  - pip install coverage python-coveralls
before_script:
  - flake8
script:
  - coverage erase
  - coverage run --source fakeredis test_fakeredis.py
notifications:
  email:
    - js@jamesls.com
    - bmerry@ska.ac.za
after_success: coveralls
