- project:
    templates:
      - neutron-tempest-plugin-jobs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - integrated-gate
      - integrated-gate-py3
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-functional
        - neutron-functional-python27
        - neutron-fullstack
        - neutron-rally-task
        - neutron-tempest-dvr
        - neutron-tempest-linuxbridge
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode
        - tempest-multinode-full-py3:
            voting: false
            # We don't run the job on things like neutron docs-only changes
            irrelevant-files: &tempest-irrelevant-files
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
        - neutron-tempest-dvr-ha-multinode-full
        - neutron-tempest-iptables_hybrid
        - neutron-tempest-iptables_hybrid-fedora
        - neutron-grenade
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full:
            timeout: 10800
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-py3:
            timeout: 10800
            irrelevant-files: *tempest-irrelevant-files
        - tempest-slow-py3:
            irrelevant-files: *tempest-irrelevant-files
        - networking-ovn-tempest-dsvm-ovs-release:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - grenade-py3:
            irrelevant-files: *tempest-irrelevant-files
        - openstacksdk-functional-devstack-networking:
            voting: false
    gate:
      jobs:
        - neutron-functional
        - neutron-functional-python27
        - neutron-fullstack
        - neutron-tempest-dvr
        - neutron-tempest-linuxbridge
        - neutron-tempest-iptables_hybrid
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode
        - neutron-grenade
        - tempest-full:
            timeout: 10800
        - tempest-full-py3:
            timeout: 10800
        - tempest-slow-py3:
            irrelevant-files: *tempest-irrelevant-files
        - grenade-py3:
            irrelevant-files: *tempest-irrelevant-files
    periodic:
      jobs:
        - neutron-functional
        - neutron-tempest-postgres-full
        - neutron-tempest-with-os-ken-master
    experimental:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-fullstack-with-uwsgi
        - neutron-tempest-with-uwsgi

        # TODO(slaweq): we should consider to convert this job to "non-legacy"
        # one and move it to check queue, at least as non-voting
        - legacy-grenade-dsvm-neutron-linuxbridge-multinode:
            irrelevant-files: *tempest-irrelevant-files

        - legacy-tempest-dsvm-neutron-full-centos-7:
            irrelevant-files: *tempest-irrelevant-files
        - legacy-tempest-dsvm-neutron-dvr-multinode-full:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-py3-opensuse150:
            irrelevant-files: *tempest-irrelevant-files

- job:
    name: neutron-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-functional/run.yaml
    post-run: playbooks/legacy/neutron-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$

- job:
    name: neutron-functional-python27
    parent: neutron-functional
    run: playbooks/legacy/neutron-functional-python27/run.yaml
    post-run: playbooks/legacy/neutron-functional-python27/post.yaml

- job:
    name: neutron-fullstack
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-fullstack/run.yaml
    post-run: playbooks/legacy/neutron-fullstack/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$


- job:
    name: neutron-rally-task
    parent: rally-task-neutron
    timeout: 7800
    vars:
      devstack_localrc:
        USE_PYTHON3: true
      devstack_plugins:
        rally-openstack: https://git.openstack.org/openstack/rally-openstack
        neutron: https://git.openstack.org/openstack/neutron
      devstack_services:
        neutron-trunk: true
      rally_task: rally-jobs/task-neutron.yaml
    required-projects:
      - openstack/rally-openstack
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: neutron-tempest-dvr
    parent: tempest-full-py3
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/tempest
    vars:
      tempest_concurrency: 4
      devstack_localrc:
        Q_DVR_MODE: dvr_snat
    irrelevant-files: *tempest-irrelevant-files

- job:
    name: neutron-tempest-linuxbridge
    parent: tempest-full-py3
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/tempest
    vars:
      tempest_concurrency: 4
      devstack_localrc:
        Q_AGENT: linuxbridge
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: neutron-grenade-multinode
    parent: legacy-dsvm-base-multinode
    run: playbooks/legacy/neutron-grenade-multinode/run.yaml
    post-run: playbooks/legacy/neutron-grenade-multinode/post.yaml
    timeout: 10800
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/neutron
    nodeset: ubuntu-xenial-2-node
    irrelevant-files: *tempest-irrelevant-files

- job:
    name: neutron-grenade-dvr-multinode
    parent: legacy-dsvm-base-multinode
    run: playbooks/legacy/neutron-grenade-dvr-multinode/run.yaml
    post-run: playbooks/legacy/neutron-grenade-dvr-multinode/post.yaml
    timeout: 7500
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/neutron
    nodeset: ubuntu-xenial-2-node
    irrelevant-files: *tempest-irrelevant-files

- job:
    name: neutron-tempest-dvr-ha-multinode-full
    parent: legacy-dsvm-base-multinode
    run: playbooks/legacy/neutron-tempest-dvr-ha-multinode-full/run.yaml
    post-run: playbooks/legacy/neutron-tempest-dvr-ha-multinode-full/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/tempest
    nodeset: ubuntu-xenial-3-node
    irrelevant-files: *tempest-irrelevant-files
    voting: false

- job:
    name: neutron-tempest-iptables_hybrid
    parent: tempest-full-py3
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/tempest
    vars:
      tempest_concurrency: 4
      devstack_plugins:
        neutron: git://git.openstack.org/openstack/neutron.git
      devstack_services:
        tls-proxy: false
        tempest: true
        neutron-dns: true
        neutron-qos: true
        neutron-segments: true
        neutron-trunk: true
        neutron-uplink-status-propagation: true
      devstack_local_conf:
        post-config:
          $NEUTRON_CONF:
            QUOTAS:
              quota_router: 100
              quota_floatingip: 500
              quota_security_group: 100
              quota_security_group_rule: 1000
          # NOTE(slaweq): We can get rid of this hardcoded absolute path when
          # devstack-tempest job will be switched to use lib/neutron instead of
          # lib/neutron-legacy
          "/$NEUTRON_CORE_PLUGIN_CONF":
            ml2_type_vlan:
              network_vlan_ranges: foo:1:10
            agent:
              enable_distributed_routing: True
              l2_population: True
              tunnel_types: vxlan,gre
            securitygroup:
              firewall_driver: iptables_hybrid
          $NEUTRON_L3_CONF:
            agent:
              availability_zone: nova
          $NEUTRON_DHCP_CONF:
            agent:
              availability_zone: nova
        test-config:
          $TEMPEST_CONFIG:
            neutron_plugin_options:
              provider_vlans: foo,
              agent_availability_zone: nova
              image_is_advanced: true
              available_type_drivers: flat,geneve,vlan,gre,local,vxlan
    irrelevant-files: *tempest-irrelevant-files

- job:
    name: neutron-tempest-iptables_hybrid-fedora
    parent: neutron-tempest-iptables_hybrid
    nodeset: devstack-single-node-fedora-latest
    irrelevant-files: *tempest-irrelevant-files
    voting: false

- job:
    name: neutron-grenade
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-grenade/run.yaml
    post-run: playbooks/legacy/neutron-grenade/post.yaml
    timeout: 10800
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/neutron
    irrelevant-files: *tempest-irrelevant-files

- job:
    name: neutron-tempest-postgres-full
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-tempest-postgres-full/run.yaml
    post-run: playbooks/legacy/neutron-tempest-postgres-full/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/tempest

- job:
    name: neutron-tempest-with-os-ken-master
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-tempest-with-os-ken-master/run.yaml
    post-run: playbooks/legacy/neutron-tempest-with-os-ken-master/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/tempest

- job:
    name: neutron-fullstack-with-uwsgi
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-fullstack-with-uwsgi/run.yaml
    post-run: playbooks/legacy/neutron-fullstack-with-uwsgi/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$
    voting: false

- job:
    name: neutron-functional-with-uwsgi
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-functional-with-uwsgi/run.yaml
    post-run: playbooks/legacy/neutron-functional-with-uwsgi/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$
    voting: false

- job:
    name: neutron-tempest-with-uwsgi
    parent: devstack-tempest
    description: Run neutron Tempest tests with uwsgi
    timeout: 8400
    required-projects:
      - openstack/neutron
      - openstack/tempest
    vars:
      tox_envlist: full
      devstack_localrc:
        NEUTRON_DEPLOY_MOD_WSGI: true
    irrelevant-files: *tempest-irrelevant-files
    voting: false
