# Generated by Django 2.1.5 on 2019-01-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_framework', '0004_auto_20190126_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitymetadata',
            name='metadata_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicemetadata',
            name='metadata_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
