# Generated by Django 2.1.5 on 2019-02-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_framework', '0011_auto_20190206_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityattribute',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceattribute',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
