# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_framework', '0016_auto_20190209_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprovider',
            name='custom_maps',
            field=models.ManyToManyField(blank=True, to='django_saml2_framework.AttributeMap'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='custom_maps',
            field=models.ManyToManyField(blank=True, to='django_saml2_framework.AttributeMap'),
        ),
    ]
