environment:
  global:
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "latest"
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
    NUMPY_VERSION: "stable"

  matrix:
    - PYTHON_VERSION: "3.7"

matrix:
  fast_finish: true
platform:
  - x64

install:
  # Install miniconda using astropy helper
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  - cmd: conda install --yes hdf5
  - "pip install -r requirements/test.txt"


# Not a .NET project, we build heliopy in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% python setup.py install"
  - "%CMD_IN_ENV% py.test"
