[tool.poetry]
name = "j5"
version = "0.0.3"
description = "J5 Robotics API"
authors = ["j5 contributors <sro@soton.ac.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pyusb = "^1.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
flake8-commas = "^2.0"
flake8-comprehensions = "^2.1"
flake8-debugger = "^3.1"
flake8-docstrings = "^1.3"
flake8-isort = "^2.6"
flake8-mutable = "^1.2"
flake8-todo = "^0.7.0"
mypy = "^0.670.0"
pytest = "^4.3"
pytest-cov = "^2.6"
sphinx = "^1.8"
sphinx-rtd-theme = "^0.4.3"
rope = "^0.12.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
