# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-07 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='userid',
        ),
        migrations.AddField(
            model_name='token',
            name='username',
            field=models.CharField(default=None, max_length=255, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
