# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_server', '0002_auto_20180828_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='ͨ通过token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='request_token',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='请求token'),
        ),
    ]
