# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-08 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_server', '0003_auto_20190308_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='ban_user_uri',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='create_user_uri',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='delete_user_uri',
        ),
        migrations.AddField(
            model_name='consumer',
            name='user_appname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户app名称'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='user_modelname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户model名称'),
        ),
    ]
