[tool.poetry]
version = "0.1.0"
name = "contenders"
readme = "README.md"
authors = ["Jeremiah Boby <mail@jeremiahboby.me>"]
description = "A self-hosted programming challenge framework."

[tool.poetry.dependencies]
python = "^3.7"
dash = "^0.40.0"
dash-bootstrap-components = "^0.3.5"
dash-table = "^3.6"
pandas = "^0.24.2"

[tool.poetry.scripts]
contender = "contenders:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
