# Generated by Django 2.0.5 on 2018-11-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlink',
            name='date_end',
            field=models.DateField(blank=True, default='9999-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='friendlink',
            name='date_start',
            field=models.DateField(auto_created=True),
        ),
    ]
