[tool.poetry]
name = "negmas"
version = "0.1.35"
description = "NEGotiations Managed by Agent Simulations"
authors = ["Yasser Mohammad <yasserfarouk@gmail.com>"]
license = "GPL-2.0+"

readme = 'README.rst'

repository = "https://github.com/yasserfarouk/negmas"
homepage = "https://github.com/yasserfarouk/negmas"

keywords = ['negotiation', 'mas', 'multi-agent', 'simulation', 'AI']

include = ["*.rst", "LICENSE"]
exclude = ["negmas/**/*.pyc", "nemgas/**/__pycache__", "config", "docs", "etc", "notebooks", "tests"]

[tool.poetry.dependencies]
python = ">=3.6"
Click = ">=6.0"
dataclasses = { version = "*", python = "<3.7" }
PyYAML = "5.1b1" # to avoid a security issue found by github
distributed = { version = "*", optional = true }
progressbar2 = "^3.39"
typing_extensions = "^3.7"
pytest-runner = "^4.4"
pandas = "^0.24.1"
scipy = "^1.2"
numpy = "^1.16"
stringcase = "^1.2"
py4j = "^0.10.8"
colorlog = "^4.0"
inflect = "^2.1"
matplotlib = "^3.0"
setuptools = "^40.8"
tabulate = "^0.8.3"
typing = "^3.6"
tox = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.0"
poetry = "*"
hypothesis = "^4.9"
tox = "^3.7"
poetry-setup = "^0.3.6"
codacy-coverage = "^1.3"

[tool.poetry.scripts]
negmas = 'negmas.scripts.negmas:cli'


#[tool.poetry.extras]
#dask = ["distributed"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

