[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pomw"
version = "0.1.0"
description = "The Pomodoro Technique using TaskWarrior and TimeWarrior"
authors = [ "Tjaart van der Walt <tjaart@tjaart.org>",]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://tjaart.gitlab.io/pomw"
repository = "https://gitlab.com/tjaart/pomw"
documentation = "https://tjaart.gitlab.io/pomw/docs"
keywords = [ "pomodoro", "timewarrior", "taskwarrior",]
classifiers = [ "Development Status :: 3 - Alpha", "Environment :: Console", "Operating System :: POSIX",]

[tool.poetry.dependencies]
python = "^3.7"
python-dateutil = "^2.7"
taskw = "^1.2"
timew = "^0.0.22"
unijson = "^1.0"
urwid = "^2.0"
semver = "^2.8"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
toml = "^0.10.0"
pytest-cov = "^2.6"
tox = "^3.7"
jedi = "^0.13.3"

[tool.poetry.scripts]
pomw = "pomw.console:main"

[tool.poetry.dev-dependencies.black]
version = "^18.3-alpha.0"
allows-prereleases = true
