---
- name: "junos: delete vlan"
  junos_command:
    commands:
      - config
      - "delete vlans {{ _vlan_name }}"
      - commit
  register: result
  retries: 10
  delay: 5
  until: result.rc is defined and result.rc == 0
  connection: network_cli
