#ifndef COMPADRE_CONFIG_H
#define COMPADRE_CONFIG_H

#define COMPADRE_DEBUG
#define COMPADRE_USE_KOKKOSCORE
#define COMPADRE_USE_LAPACK
#define COMPADRE_USE_MPI
#define COMPADRE_USE_PYTHON
#define LAPACK_DECLARED_THREADSAFE
#define COMPADRE_VERSION_MAJOR 1
#define COMPADRE_VERSION_MINOR 0
#define COMPADRE_VERSION_PATCH 1
#define COMPADRE_SEMVER "1.0.1-sha.831c712+1011010101"
#define COMPADRE_COMMIT "831c712fe742b1d0849df8f492d9e9155e527794"
#define COMPADRE_CXX_FLAGS " "
#define COMPADRE_CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX:BOOL=\"/usr/local\" -DPYTHON_CALLING_BUILD:BOOL=\"ON\" -DCompadre_USE_MPI:BOOL=\"ON\" -DCompadre_USE_PYTHON:BOOL=\"ON\" -DCompadre_USE_MATLAB:BOOL=\"ON\" -DCompadre_EXAMPLES:BOOL=\"OFF\""
#define GMLS_MODULE_DEST "lib/python/dist-packages"
#define COMPADRE_INSTALL_PREFIX "/usr/local"

#endif
