
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-07T11:37:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f201db121a2f5ead1f0c92d02daef7db4e1ca93",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
