[build-system]
requires = ["setuptools", "wheel"]

[tool.poetry]
name = "masci_tools"
version = "0.3.0"
description = "Tools for Materials science. Vis contains wrapers of matplotlib functionality to visualalize common material science data. Plus wrapers of visualisation for aiida-fleur workflow nodes"
readme = "README.md"
authors = ["Jens Bröder <j.broeder@fz-juelich.de>",
           "Philipp Rüssmann <p.ruessmann@fz-juelich.de>",
          ]
license = "MIT"
homepage = "https://github.com/JuDFTteam/masci-tools"
repository = "https://github.com/JuDFTteam/masci-tools"
documentation = "https://masci-tools.readthedocs.io"
keywords = ["material science",
            "plots",
            "visualization",
            "aiida",
            "dft"]
classifiers = ["Development Status :: 4 - Beta",
               "Intended Audience :: Science/Research",
               "License :: OSI Approved :: MIT License",
               "Programming Language :: Python :: 2.7",
               "Topic :: Scientific/Engineering :: Physics"]


[tool.poetry.dependencies]
python = "^2.7"
bumpversion = "*"
numpy = "*"
matplotlib = "*"
h5py = "*"
pytest-cov = "*"
scipy = "*"

