
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-14T07:56:06-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "6019289541e117184946c1ff8df21d7363277584",
 "version": "v0.4.61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
