# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkHistogramToRunLengthFeaturesFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkHistogramToRunLengthFeaturesFilterPython', [dirname(__file__)])
        except ImportError:
            import _itkHistogramToRunLengthFeaturesFilterPython
            return _itkHistogramToRunLengthFeaturesFilterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkHistogramToRunLengthFeaturesFilterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkHistogramToRunLengthFeaturesFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkHistogramToRunLengthFeaturesFilterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkSimpleDataObjectDecoratorPython
import itkCovariantVectorPython
import itkVectorPython
import vnl_vectorPython
import stdcomplexPython
import pyBasePython
import vnl_matrixPython
import vnl_vector_refPython
import itkFixedArrayPython
import itkRGBPixelPython
import itkRGBAPixelPython
import itkArrayPython
import ITKCommonBasePython
import itkHistogramPython
import itkSamplePython

def itkHistogramToRunLengthFeaturesFilterHD_New():
  return itkHistogramToRunLengthFeaturesFilterHD.New()


def itkHistogramToRunLengthFeaturesFilterHF_New():
  return itkHistogramToRunLengthFeaturesFilterHF.New()

class itkHistogramToRunLengthFeaturesFilterHD(ITKCommonBasePython.itkProcessObject):
    """Proxy of C++ itkHistogramToRunLengthFeaturesFilterHD class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkHistogramToRunLengthFeaturesFilterHD_Pointer"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkHistogramToRunLengthFeaturesFilterHD self) -> itkHistogramToRunLengthFeaturesFilterHD_Pointer"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_Clone(self)


    def SetInput(self, histogram):
        """SetInput(itkHistogramToRunLengthFeaturesFilterHD self, itkHistogramD histogram)"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_SetInput(self, histogram)


    def GetInput(self):
        """GetInput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkHistogramD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetInput(self)


    def GetShortRunEmphasis(self):
        """GetShortRunEmphasis(itkHistogramToRunLengthFeaturesFilterHD self) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunEmphasis(self)


    def GetShortRunEmphasisOutput(self):
        """GetShortRunEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkSimpleDataObjectDecoratorD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunEmphasisOutput(self)


    def GetLongRunEmphasis(self):
        """GetLongRunEmphasis(itkHistogramToRunLengthFeaturesFilterHD self) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunEmphasis(self)


    def GetLongRunEmphasisOutput(self):
        """GetLongRunEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkSimpleDataObjectDecoratorD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunEmphasisOutput(self)


    def GetGreyLevelNonuniformity(self):
        """GetGreyLevelNonuniformity(itkHistogramToRunLengthFeaturesFilterHD self) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetGreyLevelNonuniformity(self)


    def GetGreyLevelNonuniformityOutput(self):
        """GetGreyLevelNonuniformityOutput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkSimpleDataObjectDecoratorD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetGreyLevelNonuniformityOutput(self)


    def GetRunLengthNonuniformity(self):
        """GetRunLengthNonuniformity(itkHistogramToRunLengthFeaturesFilterHD self) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetRunLengthNonuniformity(self)


    def GetRunLengthNonuniformityOutput(self):
        """GetRunLengthNonuniformityOutput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkSimpleDataObjectDecoratorD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetRunLengthNonuniformityOutput(self)


    def GetLowGreyLevelRunEmphasis(self):
        """GetLowGreyLevelRunEmphasis(itkHistogramToRunLengthFeaturesFilterHD self) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLowGreyLevelRunEmphasis(self)


    def GetLowGreyLevelRunEmphasisOutput(self):
        """GetLowGreyLevelRunEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkSimpleDataObjectDecoratorD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLowGreyLevelRunEmphasisOutput(self)


    def GetHighGreyLevelRunEmphasis(self):
        """GetHighGreyLevelRunEmphasis(itkHistogramToRunLengthFeaturesFilterHD self) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetHighGreyLevelRunEmphasis(self)


    def GetHighGreyLevelRunEmphasisOutput(self):
        """GetHighGreyLevelRunEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkSimpleDataObjectDecoratorD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetHighGreyLevelRunEmphasisOutput(self)


    def GetShortRunLowGreyLevelEmphasis(self):
        """GetShortRunLowGreyLevelEmphasis(itkHistogramToRunLengthFeaturesFilterHD self) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunLowGreyLevelEmphasis(self)


    def GetShortRunLowGreyLevelEmphasisOutput(self):
        """GetShortRunLowGreyLevelEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkSimpleDataObjectDecoratorD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunLowGreyLevelEmphasisOutput(self)


    def GetShortRunHighGreyLevelEmphasis(self):
        """GetShortRunHighGreyLevelEmphasis(itkHistogramToRunLengthFeaturesFilterHD self) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunHighGreyLevelEmphasis(self)


    def GetShortRunHighGreyLevelEmphasisOutput(self):
        """GetShortRunHighGreyLevelEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkSimpleDataObjectDecoratorD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunHighGreyLevelEmphasisOutput(self)


    def GetLongRunLowGreyLevelEmphasis(self):
        """GetLongRunLowGreyLevelEmphasis(itkHistogramToRunLengthFeaturesFilterHD self) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunLowGreyLevelEmphasis(self)


    def GetLongRunLowGreyLevelEmphasisOutput(self):
        """GetLongRunLowGreyLevelEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkSimpleDataObjectDecoratorD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunLowGreyLevelEmphasisOutput(self)


    def GetLongRunHighGreyLevelEmphasis(self):
        """GetLongRunHighGreyLevelEmphasis(itkHistogramToRunLengthFeaturesFilterHD self) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunHighGreyLevelEmphasis(self)


    def GetLongRunHighGreyLevelEmphasisOutput(self):
        """GetLongRunHighGreyLevelEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHD self) -> itkSimpleDataObjectDecoratorD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunHighGreyLevelEmphasisOutput(self)


    def GetTotalNumberOfRuns(self):
        """GetTotalNumberOfRuns(itkHistogramToRunLengthFeaturesFilterHD self) -> unsigned long"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetTotalNumberOfRuns(self)

    ShortRunEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_ShortRunEmphasis
    LongRunEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_LongRunEmphasis
    GreyLevelNonuniformity = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GreyLevelNonuniformity
    RunLengthNonuniformity = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_RunLengthNonuniformity
    LowGreyLevelRunEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_LowGreyLevelRunEmphasis
    HighGreyLevelRunEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_HighGreyLevelRunEmphasis
    ShortRunLowGreyLevelEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_ShortRunLowGreyLevelEmphasis
    ShortRunHighGreyLevelEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_ShortRunHighGreyLevelEmphasis
    LongRunLowGreyLevelEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_LongRunLowGreyLevelEmphasis
    LongRunHighGreyLevelEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_LongRunHighGreyLevelEmphasis

    def GetFeature(self, name):
        """GetFeature(itkHistogramToRunLengthFeaturesFilterHD self, itkHistogramToRunLengthFeaturesFilterHD::RunLengthFeatureName name) -> double"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetFeature(self, name)

    __swig_destroy__ = _itkHistogramToRunLengthFeaturesFilterPython.delete_itkHistogramToRunLengthFeaturesFilterHD

    def cast(obj):
        """cast(itkLightObject obj) -> itkHistogramToRunLengthFeaturesFilterHD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self):
        """GetPointer(itkHistogramToRunLengthFeaturesFilterHD self) -> itkHistogramToRunLengthFeaturesFilterHD"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkHistogramToRunLengthFeaturesFilterHD

        Create a new object of the class itkHistogramToRunLengthFeaturesFilterHD and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHistogramToRunLengthFeaturesFilterHD.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHistogramToRunLengthFeaturesFilterHD.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHistogramToRunLengthFeaturesFilterHD.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHistogramToRunLengthFeaturesFilterHD.Clone = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_Clone, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.SetInput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_SetInput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetInput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetInput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetShortRunEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunEmphasis, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetShortRunEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetLongRunEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunEmphasis, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetLongRunEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetGreyLevelNonuniformity = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetGreyLevelNonuniformity, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetGreyLevelNonuniformityOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetGreyLevelNonuniformityOutput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetRunLengthNonuniformity = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetRunLengthNonuniformity, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetRunLengthNonuniformityOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetRunLengthNonuniformityOutput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetLowGreyLevelRunEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLowGreyLevelRunEmphasis, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetLowGreyLevelRunEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLowGreyLevelRunEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetHighGreyLevelRunEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetHighGreyLevelRunEmphasis, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetHighGreyLevelRunEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetHighGreyLevelRunEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetShortRunLowGreyLevelEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunLowGreyLevelEmphasis, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetShortRunLowGreyLevelEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunLowGreyLevelEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetShortRunHighGreyLevelEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunHighGreyLevelEmphasis, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetShortRunHighGreyLevelEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetShortRunHighGreyLevelEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetLongRunLowGreyLevelEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunLowGreyLevelEmphasis, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetLongRunLowGreyLevelEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunLowGreyLevelEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetLongRunHighGreyLevelEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunHighGreyLevelEmphasis, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetLongRunHighGreyLevelEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetLongRunHighGreyLevelEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetTotalNumberOfRuns = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetTotalNumberOfRuns, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetFeature = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetFeature, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD.GetPointer = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_GetPointer, None, itkHistogramToRunLengthFeaturesFilterHD)
itkHistogramToRunLengthFeaturesFilterHD_swigregister = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_swigregister
itkHistogramToRunLengthFeaturesFilterHD_swigregister(itkHistogramToRunLengthFeaturesFilterHD)

def itkHistogramToRunLengthFeaturesFilterHD___New_orig__():
    """itkHistogramToRunLengthFeaturesFilterHD___New_orig__() -> itkHistogramToRunLengthFeaturesFilterHD_Pointer"""
    return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD___New_orig__()

def itkHistogramToRunLengthFeaturesFilterHD_cast(obj):
    """itkHistogramToRunLengthFeaturesFilterHD_cast(itkLightObject obj) -> itkHistogramToRunLengthFeaturesFilterHD"""
    return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHD_cast(obj)

class itkHistogramToRunLengthFeaturesFilterHF(ITKCommonBasePython.itkProcessObject):
    """Proxy of C++ itkHistogramToRunLengthFeaturesFilterHF class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkHistogramToRunLengthFeaturesFilterHF_Pointer"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkHistogramToRunLengthFeaturesFilterHF self) -> itkHistogramToRunLengthFeaturesFilterHF_Pointer"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_Clone(self)


    def SetInput(self, histogram):
        """SetInput(itkHistogramToRunLengthFeaturesFilterHF self, itkHistogramF histogram)"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_SetInput(self, histogram)


    def GetInput(self):
        """GetInput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkHistogramF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetInput(self)


    def GetShortRunEmphasis(self):
        """GetShortRunEmphasis(itkHistogramToRunLengthFeaturesFilterHF self) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunEmphasis(self)


    def GetShortRunEmphasisOutput(self):
        """GetShortRunEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkSimpleDataObjectDecoratorF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunEmphasisOutput(self)


    def GetLongRunEmphasis(self):
        """GetLongRunEmphasis(itkHistogramToRunLengthFeaturesFilterHF self) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunEmphasis(self)


    def GetLongRunEmphasisOutput(self):
        """GetLongRunEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkSimpleDataObjectDecoratorF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunEmphasisOutput(self)


    def GetGreyLevelNonuniformity(self):
        """GetGreyLevelNonuniformity(itkHistogramToRunLengthFeaturesFilterHF self) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetGreyLevelNonuniformity(self)


    def GetGreyLevelNonuniformityOutput(self):
        """GetGreyLevelNonuniformityOutput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkSimpleDataObjectDecoratorF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetGreyLevelNonuniformityOutput(self)


    def GetRunLengthNonuniformity(self):
        """GetRunLengthNonuniformity(itkHistogramToRunLengthFeaturesFilterHF self) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetRunLengthNonuniformity(self)


    def GetRunLengthNonuniformityOutput(self):
        """GetRunLengthNonuniformityOutput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkSimpleDataObjectDecoratorF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetRunLengthNonuniformityOutput(self)


    def GetLowGreyLevelRunEmphasis(self):
        """GetLowGreyLevelRunEmphasis(itkHistogramToRunLengthFeaturesFilterHF self) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLowGreyLevelRunEmphasis(self)


    def GetLowGreyLevelRunEmphasisOutput(self):
        """GetLowGreyLevelRunEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkSimpleDataObjectDecoratorF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLowGreyLevelRunEmphasisOutput(self)


    def GetHighGreyLevelRunEmphasis(self):
        """GetHighGreyLevelRunEmphasis(itkHistogramToRunLengthFeaturesFilterHF self) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetHighGreyLevelRunEmphasis(self)


    def GetHighGreyLevelRunEmphasisOutput(self):
        """GetHighGreyLevelRunEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkSimpleDataObjectDecoratorF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetHighGreyLevelRunEmphasisOutput(self)


    def GetShortRunLowGreyLevelEmphasis(self):
        """GetShortRunLowGreyLevelEmphasis(itkHistogramToRunLengthFeaturesFilterHF self) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunLowGreyLevelEmphasis(self)


    def GetShortRunLowGreyLevelEmphasisOutput(self):
        """GetShortRunLowGreyLevelEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkSimpleDataObjectDecoratorF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunLowGreyLevelEmphasisOutput(self)


    def GetShortRunHighGreyLevelEmphasis(self):
        """GetShortRunHighGreyLevelEmphasis(itkHistogramToRunLengthFeaturesFilterHF self) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunHighGreyLevelEmphasis(self)


    def GetShortRunHighGreyLevelEmphasisOutput(self):
        """GetShortRunHighGreyLevelEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkSimpleDataObjectDecoratorF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunHighGreyLevelEmphasisOutput(self)


    def GetLongRunLowGreyLevelEmphasis(self):
        """GetLongRunLowGreyLevelEmphasis(itkHistogramToRunLengthFeaturesFilterHF self) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunLowGreyLevelEmphasis(self)


    def GetLongRunLowGreyLevelEmphasisOutput(self):
        """GetLongRunLowGreyLevelEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkSimpleDataObjectDecoratorF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunLowGreyLevelEmphasisOutput(self)


    def GetLongRunHighGreyLevelEmphasis(self):
        """GetLongRunHighGreyLevelEmphasis(itkHistogramToRunLengthFeaturesFilterHF self) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunHighGreyLevelEmphasis(self)


    def GetLongRunHighGreyLevelEmphasisOutput(self):
        """GetLongRunHighGreyLevelEmphasisOutput(itkHistogramToRunLengthFeaturesFilterHF self) -> itkSimpleDataObjectDecoratorF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunHighGreyLevelEmphasisOutput(self)


    def GetTotalNumberOfRuns(self):
        """GetTotalNumberOfRuns(itkHistogramToRunLengthFeaturesFilterHF self) -> unsigned long"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetTotalNumberOfRuns(self)

    ShortRunEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_ShortRunEmphasis
    LongRunEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_LongRunEmphasis
    GreyLevelNonuniformity = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GreyLevelNonuniformity
    RunLengthNonuniformity = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_RunLengthNonuniformity
    LowGreyLevelRunEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_LowGreyLevelRunEmphasis
    HighGreyLevelRunEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_HighGreyLevelRunEmphasis
    ShortRunLowGreyLevelEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_ShortRunLowGreyLevelEmphasis
    ShortRunHighGreyLevelEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_ShortRunHighGreyLevelEmphasis
    LongRunLowGreyLevelEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_LongRunLowGreyLevelEmphasis
    LongRunHighGreyLevelEmphasis = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_LongRunHighGreyLevelEmphasis

    def GetFeature(self, name):
        """GetFeature(itkHistogramToRunLengthFeaturesFilterHF self, itkHistogramToRunLengthFeaturesFilterHF::RunLengthFeatureName name) -> float"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetFeature(self, name)

    __swig_destroy__ = _itkHistogramToRunLengthFeaturesFilterPython.delete_itkHistogramToRunLengthFeaturesFilterHF

    def cast(obj):
        """cast(itkLightObject obj) -> itkHistogramToRunLengthFeaturesFilterHF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self):
        """GetPointer(itkHistogramToRunLengthFeaturesFilterHF self) -> itkHistogramToRunLengthFeaturesFilterHF"""
        return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkHistogramToRunLengthFeaturesFilterHF

        Create a new object of the class itkHistogramToRunLengthFeaturesFilterHF and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkHistogramToRunLengthFeaturesFilterHF.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkHistogramToRunLengthFeaturesFilterHF.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHistogramToRunLengthFeaturesFilterHF.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHistogramToRunLengthFeaturesFilterHF.Clone = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_Clone, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.SetInput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_SetInput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetInput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetInput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetShortRunEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunEmphasis, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetShortRunEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetLongRunEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunEmphasis, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetLongRunEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetGreyLevelNonuniformity = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetGreyLevelNonuniformity, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetGreyLevelNonuniformityOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetGreyLevelNonuniformityOutput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetRunLengthNonuniformity = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetRunLengthNonuniformity, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetRunLengthNonuniformityOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetRunLengthNonuniformityOutput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetLowGreyLevelRunEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLowGreyLevelRunEmphasis, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetLowGreyLevelRunEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLowGreyLevelRunEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetHighGreyLevelRunEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetHighGreyLevelRunEmphasis, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetHighGreyLevelRunEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetHighGreyLevelRunEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetShortRunLowGreyLevelEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunLowGreyLevelEmphasis, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetShortRunLowGreyLevelEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunLowGreyLevelEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetShortRunHighGreyLevelEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunHighGreyLevelEmphasis, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetShortRunHighGreyLevelEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetShortRunHighGreyLevelEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetLongRunLowGreyLevelEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunLowGreyLevelEmphasis, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetLongRunLowGreyLevelEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunLowGreyLevelEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetLongRunHighGreyLevelEmphasis = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunHighGreyLevelEmphasis, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetLongRunHighGreyLevelEmphasisOutput = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetLongRunHighGreyLevelEmphasisOutput, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetTotalNumberOfRuns = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetTotalNumberOfRuns, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetFeature = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetFeature, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF.GetPointer = new_instancemethod(_itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_GetPointer, None, itkHistogramToRunLengthFeaturesFilterHF)
itkHistogramToRunLengthFeaturesFilterHF_swigregister = _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_swigregister
itkHistogramToRunLengthFeaturesFilterHF_swigregister(itkHistogramToRunLengthFeaturesFilterHF)

def itkHistogramToRunLengthFeaturesFilterHF___New_orig__():
    """itkHistogramToRunLengthFeaturesFilterHF___New_orig__() -> itkHistogramToRunLengthFeaturesFilterHF_Pointer"""
    return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF___New_orig__()

def itkHistogramToRunLengthFeaturesFilterHF_cast(obj):
    """itkHistogramToRunLengthFeaturesFilterHF_cast(itkLightObject obj) -> itkHistogramToRunLengthFeaturesFilterHF"""
    return _itkHistogramToRunLengthFeaturesFilterPython.itkHistogramToRunLengthFeaturesFilterHF_cast(obj)



