
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-11T08:06:47-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a74920d74999c2985af1f7b0275c19ce60e1b469",
 "version": "v0.4.51"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
