
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-11T16:48:05-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8ebb792fce8708381d1a31362b3613d0ac0386e",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
