
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "351aa337be4ec5ab5f22e63f3a7f84796c843159",
 "version": "0.13.1.b3805"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
