[tool.poetry]
name = "mudkip"
version = "0.1.2"
description = "A friendly Sphinx wrapper"
authors = ["Valentin Berlier <berlier.v@gmail.com>"]
license = "MIT"

homepage = "https://github.com/vberlier/mudkip"
repository = "https://github.com/vberlier/mudkip"
documentation = "https://github.com/vberlier/mudkip"

readme = "README.md"

keywords = [
]

[tool.poetry.dependencies]
python = "^3.7"
sphinx = "^1.8"
click = "^7.0"
recommonmark = "^0.5.0"
watchdog = "^0.9.0"

[tool.poetry.dev-dependencies]
black = { version = "^18.3-alpha.0", allows-prereleases = true }

[tool.poetry.scripts]
mudkip = 'mudkip.cli:mudkip'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
