# Permissions ###
ADMIN = 'ADMIN'
SYS_ADMIN = 'SYS_ADMIN'
LICENSED_USER = 'LICENSED_USER'
PROJECT_ADMIN = 'PROJECT_ADMIN'
PROJECT_CREATE = 'PROJECT_CREATE'
PROJECT_READ = 'PROJECT_READ'
PROJECT_VIEW = 'PROJECT_VIEW'
APP_ADMIN = 'APP_ADMIN'
APP_WRITE = 'APP_WRITE'
APP_READ = 'APP_READ'

BITBUCKET_PERMISSIONS = (
    (ADMIN, 'ADMIN'),
    (SYS_ADMIN, 'SYS_ADMIN'),
    (LICENSED_USER, 'LICENSED_USER'),

    (PROJECT_ADMIN, 'PROJECT_ADMIN'),
    (PROJECT_CREATE, 'PROJECT_CREATE'),
    (PROJECT_READ, 'PROJECT_READ'),
    (PROJECT_VIEW, 'PROJECT_VIEW'),

    (APP_ADMIN, 'REPO_ADMIN'),
    (APP_WRITE, 'REPO_WRITE'),
    (APP_READ, 'REPO_READ')
)

BITBUCKET_PROJECT_PERMISSIONS = (
    (PROJECT_ADMIN, 'PROJECT_ADMIN'), (PROJECT_CREATE, 'PROJECT_CREATE'),
    (PROJECT_READ, 'PROJECT_READ'), (PROJECT_VIEW, 'PROJECT_VIEW'),
)

BITBUCKET_APP_PERMISSIONS = (
    (APP_ADMIN, 'REPO_ADMIN'), (APP_WRITE, 'REPO_WRITE'), (APP_READ, 'REPO_READ'),
)

# Merges ###
MERGE_EXCLUDE = 'EXCLUDE'
MERGE_INCLUDE = 'INCLUDE'
MERGE_ONLY = 'ONLY'

BITBUCKET_MERGES_CONTROL = (
    (MERGE_EXCLUDE, 'EXCLUDE'),
    (MERGE_INCLUDE, 'INCLUDE'),
    (MERGE_ONLY, 'ONLY'),
)

BITBUCKET_MERGES_CONTROL_SERVICE_MAP = {
    MERGE_EXCLUDE: 'exclude',
    MERGE_INCLUDE: 'include',
    MERGE_ONLY: 'only',
}

# Datetime ###
MAX_TIMESTAMP = 9999999999

# Tags ###
DEFAULT_COMMIT_HISTORY_TAGS_LIMIT = 25  # default limit for number of tags to fetch on getting commit history

# Result Messages
RESPONSE_OK = 'OK'
RESPONSE_ERROR_FETCHING_TAGS = 'ERROR_FETCHING_TAGS'
