# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonstuff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='site',
        ),
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
