[tool.poetry]
name = "agw"
version = "0.2.1-beta"
description = "A pyautogui wrapper library for data entry macros."
authors = ["Mark Gemmill <contact@markgemmill.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pyautogui = "^0.9.41"
cutie = "^0.2.2"
pyobjc-core = {version = "^5.1",platform = "darwin"}
pyobjc-framework-Quartz = {version = "^5.1",platform = "darwin"}

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.dover]
versioned_files = ["pyproject.toml", "src/agw/__init__.py"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
