# we want to make sure it is run on trusty where sudo is provided for postgres
language: python
sudo: true
python:
  - "3.6"
sudo: required
env:
  - DATABASE=postgresql

services:
  - postgresql
  - docker
# make sure we're on the latest version of postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database guillotina;' -U postgres

install:
  - pip install -e .[test]
  - pip install flake8 codecov pytest-cov
script:
  - flake8 guillotina_pgcatalog
  - pytest -s --cov=guillotina_pgcatalog -s --tb=native -v --cov-report term-missing --cov-append ./guillotina_pgcatalog
after_success:
  - codecov
