class Denominations:
    width = "width"
    height = "hight"
    channels = "channels"
    data_format = "data_format"
    normalize = "normalize"
    preserve_aspect_ratio = "preserve_aspect_ratio"
    num_threads = "num_threads"
    batch_size = "batch_size"
    label_format = "label_format"
