language: python
python:
    - "2.7" 
    - "3.4"
    - "3.5"
    - "3.6"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - gcc-6

# command to install dependencies      
install:
    - pip install -r requirements.txt 
    - export CXX="g++-6" CC="gcc-6"

# command to run tests
script:
    - nosetests
