# Generated by Django 2.1.7 on 2019-03-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdjango', '0004_auto_20190313_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahmin',
            name='beklenen',
            field=models.TextField(blank=True, help_text='Beklenen etiket.'),
        ),
        migrations.AlterField(
            model_name='tahmin',
            name='tahmin',
            field=models.TextField(blank=True, help_text='Algoritmanın tahmin ettiği etiket.'),
        ),
    ]
