[tool.poetry]
name = "adp-webscrape"
version = "0.1.0"
readme = "README.rst"
description = "Log into and download reports from ADP Resource and ezLaborManager."
authors = ["Liam Corbett"]
license = "MIT"
packages = [
    { include = "adpwebscrape" }
]

[tool.poetry.dependencies]
python = "^3.7"
selenium = "^3.141"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
