language: cpp

dist: xenial
sudo: true

matrix:
  include:
    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang
      env: DEPLOY=true
      before_script:
        - meson --unity=on --buildtype=release --strip -Ddebug=true --prefix=$PWD --bindir=$OTS-$TRAVIS_OS_NAME build
      before_deploy:
        - ninja -C build install
        - ninja -C build dist
        - zip -r $OTS-$TRAVIS_OS_NAME.zip $OTS-$TRAVIS_OS_NAME

    - os: linux
      compiler: clang
      before_script:
        - meson -Db_sanitize=address,undefined build

    - os: osx
      compiler: clang
      env: DEPLOY=true
      before_install:
        - brew update
        - brew upgrade python
        - brew install ninja
      before_script:
        - meson --unity=on --buildtype=release --strip -Ddebug=true --prefix=$PWD --bindir=$OTS-$TRAVIS_OS_NAME build
      before_deploy:
        - ninja -C build install
        - zip -r $OTS-$TRAVIS_OS_NAME.zip $OTS-$TRAVIS_OS_NAME
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew

addons:
  apt:
    packages:
      - fonts-inconsolata
      - fonts-takao-gothic
      - fonts-takao-mincho
      - fonts-takao-pgothic
      - ninja-build
      - python3-pip
      - python3-setuptools

install:
  - export OTS=ots-$(grep -m1 version meson.build | cut -d"'" -f2)
  - pip3 install meson

before_script:
  - meson build

script:
  - ninja -C build
  - ninja -C build test

deploy:
  provider: releases
  api_key:
    - secure: "TLW/tIpobbvcJvEyZNJcdUL1c1Xt91vaxMegUGKvXnyT56Rxn6joLYUVhfFmz6cOKtDG4F409aAXJr60BL8iQ/xra9a8uD4Y+WKgPinQo9O8CViv1bsQpGV2rfBpNQ5UUYU/t09ReicPQNHGb0ONFRnLxmcQLo8eJzlKE1MdOoA="
  file:
    - "${OTS}-${TRAVIS_OS_NAME}.zip"
    - "build/meson-dist/${OTS}.tar.xz"
  skip_cleanup: true
  draft: true
  overwrite: true
  tag_name: $TRAVIS_TAG
  on:
    tags: true
    branch: master
    condition: $DEPLOY = true
