
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "be8166ea2185cef4412213d60ddc4282692bdee4",
 "version": "2089"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
