
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-13T15:09:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "62d99186ff6292a0adcef70d1154a0597631616e",
 "version": "0.0.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
