
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-21T15:49:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "876563f342c1f2780ee67eeca349d769c9d1d8ba",
 "version": "2019.0321.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
