
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-25T17:55:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "25e2c567773cfce9873ab5592fd91fe4930f671e",
 "version": "0.0.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
