[tool.poetry]
name = "dataland"
version = "0.1.5"
description = "Miscellaneous utilities and tools for daily data research/developments"
authors = ["Ryan <ryanchao2012@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.6"
cattrs = "^0.9.0"
regex = "^2019.2"
zhon = "^1.1"
python-box = "^3.2"
pyspark = "~2.3"
google-api-core = "~1.8"
google-api-python-client = "~1.7"
google-auth = "~1.5"
google-auth-httplib2 = "~0.0"
google-cloud-bigquery = "~1.5"
google-cloud-core = "~0.28"
google-cloud-storage = "~1.11"
google-resumable-media = "~0.3"
googleapis-common-protos = "~1.5"
oauth2client = "~3.0"
python-dateutil = "^2.8"
google-cloud-dataproc = "~0.3"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
ipython = "^7.3"
black = "^18.3-alpha.0"
flake8 = "^3.7"
autoflake = "^1.2"
isort = "^4.3"
pytest-mock = "^1.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
