# Generated by Django 2.1.7 on 2019-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('handler', models.CharField(max_length=100)),
                ('request_uri', models.URLField(max_length=512)),
                ('request_method', models.CharField(max_length=10)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_code', models.IntegerField()),
                ('response_body', models.TextField(blank=True, null=True)),
                ('request_headers', models.ManyToManyField(related_name='requested', to='webhooks.Header')),
                ('response_headers', models.ManyToManyField(related_name='responded', to='webhooks.Header')),
            ],
            options={
                'ordering': ('-sent',),
            },
        ),
    ]
