depends = ('ITKPyBase', 'ITKMesh', 'ITKIOImageBase', )
templates = (
  ('MeshIOBase', 'itk::MeshIOBase', 'itkMeshIOBase', True),
  ('MeshIOFactory', 'itk::MeshIOFactory', 'itkMeshIOFactory', True),
  ('BYUMeshIO', 'itk::BYUMeshIO', 'itkBYUMeshIO', True),
  ('BYUMeshIOFactory', 'itk::BYUMeshIOFactory', 'itkBYUMeshIOFactory', True),
  ('FreeSurferAsciiMeshIO', 'itk::FreeSurferAsciiMeshIO', 'itkFreeSurferAsciiMeshIO', True),
  ('FreeSurferAsciiMeshIOFactory', 'itk::FreeSurferAsciiMeshIOFactory', 'itkFreeSurferAsciiMeshIOFactory', True),
  ('FreeSurferBinaryMeshIO', 'itk::FreeSurferBinaryMeshIO', 'itkFreeSurferBinaryMeshIO', True),
  ('FreeSurferBinaryMeshIOFactory', 'itk::FreeSurferBinaryMeshIOFactory', 'itkFreeSurferBinaryMeshIOFactory', True),
  ('MeshFileReader', 'itk::MeshFileReader', 'itkMeshFileReaderMF2STF22FF', True, 'itk::Mesh< float,2,itk::DefaultStaticMeshTraits< float,2,2,float,float > >'),
  ('MeshFileReader', 'itk::MeshFileReader', 'itkMeshFileReaderMF2DTF22FF', True, 'itk::Mesh< float,2,itk::DefaultDynamicMeshTraits< float,2,2,float,float > >'),
  ('MeshFileReader', 'itk::MeshFileReader', 'itkMeshFileReaderMD2STD22DD', True, 'itk::Mesh< double,2,itk::DefaultStaticMeshTraits< double,2,2,double,double > >'),
  ('MeshFileReader', 'itk::MeshFileReader', 'itkMeshFileReaderMD2DTD22DD', True, 'itk::Mesh< double,2,itk::DefaultDynamicMeshTraits< double,2,2,double,double > >'),
  ('MeshFileReader', 'itk::MeshFileReader', 'itkMeshFileReaderMF3STF33FF', True, 'itk::Mesh< float,3,itk::DefaultStaticMeshTraits< float,3,3,float,float > >'),
  ('MeshFileReader', 'itk::MeshFileReader', 'itkMeshFileReaderMF3DTF33FF', True, 'itk::Mesh< float,3,itk::DefaultDynamicMeshTraits< float,3,3,float,float > >'),
  ('MeshFileReader', 'itk::MeshFileReader', 'itkMeshFileReaderMD3STD33DD', True, 'itk::Mesh< double,3,itk::DefaultStaticMeshTraits< double,3,3,double,double > >'),
  ('MeshFileReader', 'itk::MeshFileReader', 'itkMeshFileReaderMD3DTD33DD', True, 'itk::Mesh< double,3,itk::DefaultDynamicMeshTraits< double,3,3,double,double > >'),
  ('MeshFileWriter', 'itk::MeshFileWriter', 'itkMeshFileWriterMF2STF22FF', True, 'itk::Mesh< float,2,itk::DefaultStaticMeshTraits< float,2,2,float,float > >'),
  ('MeshFileWriter', 'itk::MeshFileWriter', 'itkMeshFileWriterMF2DTF22FF', True, 'itk::Mesh< float,2,itk::DefaultDynamicMeshTraits< float,2,2,float,float > >'),
  ('MeshFileWriter', 'itk::MeshFileWriter', 'itkMeshFileWriterMD2STD22DD', True, 'itk::Mesh< double,2,itk::DefaultStaticMeshTraits< double,2,2,double,double > >'),
  ('MeshFileWriter', 'itk::MeshFileWriter', 'itkMeshFileWriterMD2DTD22DD', True, 'itk::Mesh< double,2,itk::DefaultDynamicMeshTraits< double,2,2,double,double > >'),
  ('MeshFileWriter', 'itk::MeshFileWriter', 'itkMeshFileWriterMF3STF33FF', True, 'itk::Mesh< float,3,itk::DefaultStaticMeshTraits< float,3,3,float,float > >'),
  ('MeshFileWriter', 'itk::MeshFileWriter', 'itkMeshFileWriterMF3DTF33FF', True, 'itk::Mesh< float,3,itk::DefaultDynamicMeshTraits< float,3,3,float,float > >'),
  ('MeshFileWriter', 'itk::MeshFileWriter', 'itkMeshFileWriterMD3STD33DD', True, 'itk::Mesh< double,3,itk::DefaultStaticMeshTraits< double,3,3,double,double > >'),
  ('MeshFileWriter', 'itk::MeshFileWriter', 'itkMeshFileWriterMD3DTD33DD', True, 'itk::Mesh< double,3,itk::DefaultDynamicMeshTraits< double,3,3,double,double > >'),
  ('OBJMeshIO', 'itk::OBJMeshIO', 'itkOBJMeshIO', True),
  ('OBJMeshIOFactory', 'itk::OBJMeshIOFactory', 'itkOBJMeshIOFactory', True),
  ('OFFMeshIO', 'itk::OFFMeshIO', 'itkOFFMeshIO', True),
  ('OFFMeshIOFactory', 'itk::OFFMeshIOFactory', 'itkOFFMeshIOFactory', True),
  ('VTKPolyDataMeshIO', 'itk::VTKPolyDataMeshIO', 'itkVTKPolyDataMeshIO', True),
  ('VTKPolyDataMeshIOFactory', 'itk::VTKPolyDataMeshIOFactory', 'itkVTKPolyDataMeshIOFactory', True),
)
