# Generated by Django 2.1 on 2018-08-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woordeboek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': 'Credentials', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
    ]
